<?php

declare(strict_types=1);

namespace MSSTC4PHP\DtoGenerator\Infrastructure\Emitter;

use LogicException;
use MSSTC4PHP\DtoGenerator\Application\Port\CodeEmitter;
use MSSTC4PHP\DtoGenerator\Domain\Model\ClassKind;
use MSSTC4PHP\DtoGenerator\Domain\Model\ClassModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\ClassName;
use MSSTC4PHP\DtoGenerator\Domain\Model\DiscriminatorValues;
use MSSTC4PHP\DtoGenerator\Domain\Model\DocModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\EnumModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\EnumType;
use MSSTC4PHP\DtoGenerator\Domain\Model\Identifier;
use MSSTC4PHP\DtoGenerator\Domain\Model\ListType;
use MSSTC4PHP\DtoGenerator\Domain\Model\NullableType;
use MSSTC4PHP\DtoGenerator\Domain\Model\PropertyModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\TypeModel;
use MSSTC4PHP\DtoGenerator\Domain\Shared\DefaultValue;
use MSSTC4PHP\DtoGenerator\Domain\Shared\Json;
use MSSTC4PHP\DtoGenerator\Domain\Target\Capability;
use MSSTC4PHP\DtoGenerator\Domain\Target\ClassForm;
use MSSTC4PHP\DtoGenerator\Domain\Target\TargetProfile;
use MSSTC4PHP\DtoGenerator\Domain\Target\WitherStyle;
use PhpParser\BuilderFactory;
use PhpParser\Comment;
use PhpParser\Comment\Doc;
use PhpParser\Modifiers;
use PhpParser\Node;
use PhpParser\Node\Arg;
use PhpParser\Node\ArrayItem;
use PhpParser\Node\DeclareItem;
use PhpParser\Node\Expr;
use PhpParser\Node\Expr\Array_;
use PhpParser\Node\Expr\Assign;
use PhpParser\Node\Expr\BinaryOp\BooleanAnd;
use PhpParser\Node\Expr\BinaryOp\Concat;
use PhpParser\Node\Expr\BinaryOp\Identical;
use PhpParser\Node\Expr\BinaryOp\NotIdentical;
use PhpParser\Node\Expr\ClassConstFetch;
use PhpParser\Node\Expr\Clone_;
use PhpParser\Node\Expr\ConstFetch;
use PhpParser\Node\Expr\FuncCall;
use PhpParser\Node\Expr\New_;
use PhpParser\Node\Expr\PropertyFetch;
use PhpParser\Node\Expr\StaticCall;
use PhpParser\Node\Expr\Ternary;
use PhpParser\Node\Expr\Throw_;
use PhpParser\Node\Expr\Variable;
use PhpParser\Node\Name;
use PhpParser\Node\Name\FullyQualified;
use PhpParser\Node\Param;
use PhpParser\Node\Scalar\Int_;
use PhpParser\Node\Scalar\String_;
use PhpParser\Node\Stmt;
use PhpParser\Node\Stmt\Class_;
use PhpParser\Node\Stmt\ClassMethod;
use PhpParser\Node\Stmt\Declare_;
use PhpParser\Node\Stmt\Expression;
use PhpParser\Node\Stmt\If_;
use PhpParser\Node\Stmt\Nop;
use PhpParser\Node\Stmt\Property;
use PhpParser\Node\Stmt\Return_;
use PhpParser\Node\Stmt\Use_;
use PhpParser\PhpVersion as ParserPhpVersion;

/**
 * Renders one IR class as a PHP file in the shape the target dictates (spec §6.2).
 *
 * @phpstan-import-type JsonValue from Json
 */
final class PhpParserEmitter implements CodeEmitter
{
    private const HEADER = '// @generated by msstc4php/dto-generator — DO NOT EDIT';

    private BuilderFactory $factory;

    public function __construct()
    {
        $this->factory = new BuilderFactory();
    }

    public function emit(ClassModel $class, TargetProfile $target, array $inherited = []): string
    {
        $this->assertSupported($class, $inherited);
        [$node, $names] = $this->declare($class, $target, $inherited, []);
        // Only once the class is written are all its short names known; an alias that takes one is written in full.
        $collisions = $names->collisions($class->name()->shortName());
        if ($collisions !== []) {
            [$node, $names] = $this->declare($class, $target, $inherited, $collisions);
        }

        return $this->file($node, $class->name(), $target, $names->uses());
    }

    /**
     * @param list<PropertyModel> $inherited
     * @param list<string> $refused lower-cased import aliases to write in full
     *
     * @return array{Class_, AttributeNames}
     */
    private function declare(ClassModel $class, TargetProfile $target, array $inherited, array $refused): array
    {
        $shape = new ClassShape($class, $inherited, $target->classFormFor($class->mutability()), $target);
        $form = $shape->form();
        $types = new TypeRenderer($class->name()->namespace(), $target);
        $names = new AttributeNames($types, $refused);
        $attributes = new AttributeRenderer($types, $this->factory, $names, $target->metadata());
        $annotations = new AnnotationRenderer($types, $names, $target->metadata());

        $members = [];
        if (!$form->isPromoted()) {
            // Declared in constructor order, like promoted properties, so the object layout is the same on every target.
            foreach ($this->constructorOrder($class->properties()) as $property) {
                $members[] = $this->declaration($property, $shape, $types, $attributes, $annotations);
            }
        }

        if ($shape->all() !== []) {
            $members[] = $this->constructor($shape, $types, $attributes, $annotations);
        }

        foreach ($inherited as $property) {
            if ($shape->declaresInheritedWithers() && $shape->hasMutators($property)) {
                $members[] = $this->mutator($shape, 'with' . Identifier::asciiUpperFirst($property->name()), $property, $types, $this->witherBody($shape, $property));
            }
        }

        foreach ($class->properties() as $property) {
            array_push($members, ...$this->accessors($shape, $property, $types));
        }

        $builder = $this->factory->class($class->name()->shortName())->addStmts($members);
        $parent = $class->parent();
        if ($parent instanceof ClassName) {
            $builder->extend($types->nameOf($parent));
        }

        $node = $builder->getNode();
        $node->flags = $this->modifiers($class->kind(), $form);
        $node->attrGroups = $attributes->groups($class->attributes());
        $this->document($node, DocBlock::render($class->doc()->description(), array_merge($this->deprecation($class->doc()), $annotations->annotations($class->attributes()))));

        return [$node, $names];
    }

    public function emitEnum(EnumModel $enum, TargetProfile $target): string
    {
        $native = $target->supports(Capability::from(Capability::ENUMS));
        $members = [];
        foreach ($enum->cases() as $case) {
            $member = $native
                ? $this->factory->enumCase($case->name())->setValue($case->value())->getNode()
                : $this->factory->classConst($case->name(), $case->value())->makePublic()->getNode();
            $this->document($member, DocBlock::render($case->doc()->description(), $this->deprecation($case->doc())));
            $members[] = $member;
        }

        if ($native) {
            $node = $this->factory->enum($enum->name()->shortName())->setScalarType($enum->backing()->value())->addStmts($members)->getNode();
        } else {
            // Only the constants are meant to be used; nothing should create an instance.
            $members[] = $this->factory->method('__construct')->makePrivate()->getNode();
            $node = $this->factory->class($enum->name()->shortName())->makeFinal()->addStmts($members)->getNode();
        }

        $this->document($node, DocBlock::render($enum->doc()->description(), $this->deprecation($enum->doc())));

        return $this->file($node, $enum->name(), $target);
    }

    /**
     * @param list<Use_> $uses
     */
    private function file(Stmt $declaration, ClassName $name, TargetProfile $target, array $uses = []): string
    {
        $header = new Nop();
        $header->setAttribute('comments', [new Comment(self::HEADER)]);

        $statements = [$header, new Declare_([new DeclareItem('strict_types', new Int_(1))])];
        $namespace = $name->namespace();
        if ($namespace === '') {
            array_push($statements, ...$uses, ...[$declaration]);
        } else {
            $statements[] = $this->factory->namespace($namespace)->addStmts(array_merge($uses, [$declaration]))->getNode();
        }

        $printer = new GeneratedCodePrinter([
            'phpVersion' => ParserPhpVersion::fromComponents($target->php()->major(), $target->php()->minor()),
            'shortArraySyntax' => true,
        ]);

        return $printer->prettyPrintFile($statements) . "\n";
    }

    /**
     * @param list<PropertyModel> $inherited
     */
    private function assertSupported(ClassModel $class, array $inherited): void
    {
        $fqcn = $class->name()->fqcn();
        if ($inherited !== [] && !$class->parent() instanceof ClassName) {
            throw new LogicException(sprintf('%s inherits properties but extends no class.', $fqcn));
        }

        $names = array_map(static fn (PropertyModel $property): string => $property->name(), array_merge($inherited, $class->properties()));
        foreach ($class->discriminatorValues() as $values) {
            if (!in_array($values->property(), $names, true)) {
                throw new LogicException(sprintf('%s checks the discriminator $%s, which it neither declares nor inherits.', $fqcn, $values->property()));
            }
        }
    }

    private function modifiers(ClassKind $kind, ClassForm $form): int
    {
        $flags = $form->isReadonlyClass() ? Modifiers::READONLY : 0;
        if ($kind->isAbstract()) {
            return $flags | Modifiers::ABSTRACT;
        }

        return $kind->equals(ClassKind::from(ClassKind::FINAL)) ? $flags | Modifiers::FINAL : $flags;
    }

    private function declaration(PropertyModel $property, ClassShape $shape, TypeRenderer $types, AttributeRenderer $attributes, AnnotationRenderer $annotations): Property
    {
        $builder = $this->factory->property($property->name());
        // The builder declares a property public unless told otherwise; declared (unpromoted) properties exist
        // only below PHP 8.0, so they are never readonly.
        if (!$shape->form()->hasPublicProperties()) {
            $shape->isBase() ? $builder->makeProtected() : $builder->makePrivate();
        }

        $declared = $shape->declaredType($property);
        $type = $types->nativeNode($declared);
        if ($type instanceof Node) {
            $builder->setType($type);
        }

        $node = $builder->getNode();
        $node->attrGroups = $attributes->groups($property->attributes());
        $this->document($node, $this->propertyDoc($property, $types, $annotations, $declared));

        return $node;
    }

    /**
     * Inherited parameters are plain and go to the parent constructor; the class's own are promoted or assigned.
     */
    private function constructor(ClassShape $shape, TypeRenderer $types, AttributeRenderer $attributes, AnnotationRenderer $annotations): ClassMethod
    {
        $form = $shape->form();
        $params = [];
        $tags = [];
        $body = [];
        foreach ($shape->checks() as [$property, $values]) {
            $body[] = $this->check($shape, $property, $values, $types);
        }

        if ($shape->inherited() !== []) {
            $args = array_map(static fn (PropertyModel $property): Arg => new Arg(new Variable($property->name())), $this->constructorOrder($shape->inherited()));
            $body[] = new Expression(new StaticCall(new Name('parent'), '__construct', $args));
        }

        foreach ($this->parameters($shape) as $property) {
            $param = $this->param($property, $types, $shape->defaultOf($property));
            if (!$shape->owns($property)) {
                $tags = array_merge($tags, $this->paramTag($property, $types));
            } elseif ($form->isPromoted()) {
                $param->attrGroups = $attributes->groups($property->attributes());
                $param->flags = ($form->hasPublicProperties() ? Modifiers::PUBLIC : $shape->visibility())
                    | ($form->hasReadonlyProperties() ? Modifiers::READONLY : 0);
                $this->document($param, $this->propertyDoc($property, $types, $annotations, $property->type()));
            } else {
                $tags = array_merge($tags, $this->paramTag($property, $types));
                $body[] = new Expression(new Assign($this->fetch($property->name()), new Variable($property->name())));
            }

            $params[] = $param;
        }

        // Only subclasses construct an abstract base.
        $method = $this->factory->method('__construct')->addParams($params)->addStmts($body);
        $shape->isAbstract() ? $method->makeProtected() : $method->makePublic();
        $node = $method->getNode();
        $this->document($node, DocBlock::render(null, $tags));

        return $node;
    }

    /**
     * @return list<ClassMethod>
     */
    private function accessors(ClassShape $shape, PropertyModel $property, TypeRenderer $types): array
    {
        $form = $shape->form();
        $name = $property->name();
        $suffix = Identifier::asciiUpperFirst($name);
        $deprecation = $this->deprecation($property->doc());
        $methods = [];

        if ($form->hasGetters()) {
            $getter = $this->factory->method('get' . $suffix)->makePublic()->addStmt(new Return_($this->fetch($name)));
            $declared = $shape->declaredType($property);
            $type = $types->nativeNode($declared);
            if ($type instanceof Node) {
                $getter->setReturnType($type);
            }

            $node = $getter->getNode();
            $returnTag = $types->tags($declared, 'return');
            $this->document($node, DocBlock::render(null, array_merge($returnTag, $deprecation)));
            $methods[] = $node;
        }

        if ($form->hasSetters() && $shape->hasMutators($property)) {
            $methods[] = $this->mutator($shape, 'set' . $suffix, $property, $types, [
                new Expression(new Assign($this->fetch($name), new Variable($name))),
                new Return_(new Variable('this')),
            ]);
        }

        if ($shape->hasWithers() && $shape->hasMutators($property)) {
            $methods[] = $this->mutator($shape, 'with' . $suffix, $property, $types, $this->witherBody($shape, $property));
        }

        return $methods;
    }

    /**
     * @param list<Stmt> $body
     */
    private function mutator(ClassShape $shape, string $method, PropertyModel $property, TypeRenderer $types, array $body): ClassMethod
    {
        $node = $this->factory->method($method)
            ->makePublic()
            ->addParam($this->param($property, $types, null))
            ->setReturnType($shape->returnType())
            ->addStmts($body)
            ->getNode()
        ;
        $tags = array_merge($this->paramTag($property, $types), $shape->returnTag(), $this->deprecation($property->doc()));
        $this->document($node, DocBlock::render(null, $tags));

        return $node;
    }

    /**
     * @return list<Stmt>
     */
    private function witherBody(ClassShape $shape, PropertyModel $property): array
    {
        $name = $property->name();
        $style = $shape->witherStyle();
        if ($style->equals(WitherStyle::from(WitherStyle::CLONE_WITH))) {
            $changes = new Array_([new ArrayItem(new Variable($name), new String_($name))]);

            return [new Return_(new FuncCall(new Name('clone'), [new Arg(new Variable('this')), new Arg($changes)]))];
        }

        if ($style->equals(WitherStyle::from(WitherStyle::NEW_SELF))) {
            $args = [];
            foreach ($this->parameters($shape) as $other) {
                $args[] = new Arg($other === $property ? new Variable($name) : $this->fetch($other->name()));
            }

            return [new Return_(new New_(new Name('self'), $args))];
        }

        // The copy must not shadow the parameter, which carries the property's own name.
        $copy = $name === 'clone' ? 'copy' : 'clone';

        return [
            new Expression(new Assign(new Variable($copy), new Clone_(new Variable('this')))),
            new Expression(new Assign(new PropertyFetch(new Variable($copy), $name), new Variable($name))),
            new Return_(new Variable($copy)),
        ];
    }

    private function param(PropertyModel $property, TypeRenderer $types, ?DefaultValue $default): Param
    {
        $builder = $this->factory->param($property->name());
        $type = $types->nativeNode($property->type());
        if ($type instanceof Node) {
            $builder->setType($type);
        }

        $param = $builder->getNode();
        if ($default instanceof DefaultValue) {
            $param->default = $this->defaultValue($default->value(), $property->type(), $types);
        }

        return $param;
    }

    /**
     * @return list<string>
     */
    private function paramTag(PropertyModel $property, TypeRenderer $types): array
    {
        return $types->tags($property->type(), 'param', ' $' . $property->name());
    }

    private function propertyDoc(PropertyModel $property, TypeRenderer $types, AnnotationRenderer $annotations, TypeModel $declared): ?string
    {
        $var = $types->tags($declared, 'var');

        return DocBlock::render($property->doc()->description(), array_merge($var, $this->deprecation($property->doc()), $annotations->annotations($property->attributes())));
    }

    /**
     * Required parameters first (spec §5.2): an optional one before a required one is deprecated since PHP 8.0.
     *
     * @param list<PropertyModel> $properties
     *
     * @return list<PropertyModel>
     */
    private function constructorOrder(array $properties): array
    {
        $required = [];
        $optional = [];
        foreach ($properties as $property) {
            if ($property->isRequired()) {
                $required[] = $property;
            } else {
                $optional[] = $property;
            }
        }

        return array_merge($required, $optional);
    }

    /**
     * A discriminator defaulting to the one value that selects the class counts as optional, so it moves behind the
     * required parameters; the parent call keeps the parent's order, as it passes variables.
     *
     * @return list<PropertyModel>
     */
    private function parameters(ClassShape $shape): array
    {
        $required = [];
        $optional = [];
        foreach ($this->constructorOrder($shape->all()) as $property) {
            if ($shape->defaultOf($property) instanceof DefaultValue) {
                $optional[] = $property;
            } else {
                $required[] = $property;
            }
        }

        return array_merge($required, $optional);
    }

    /**
     * `new Cat('dog')` must fail: read back, the object would claim to be a Dog.
     */
    private function check(ClassShape $shape, PropertyModel $property, DiscriminatorValues $selection, TypeRenderer $types): If_
    {
        $parameter = new Variable($property->name());
        $values = $selection->values();
        $condition = new NotIdentical($parameter, $this->defaultValue($values[0], $property->type(), $types));
        foreach (array_slice($values, 1) as $value) {
            $condition = new BooleanAnd($condition, new NotIdentical($parameter, $this->defaultValue($value, $property->type(), $types)));
        }

        // The wire name is free text; sprintf() must not read a "%" in it as a conversion. The value is quoted, null not.
        $placeholder = $property->type() instanceof NullableType ? '%%s' : '"%%s"';
        $format = sprintf($placeholder . ' does not select %s by "%s".', $shape->className()->shortName(), str_replace('%', '%%', $property->wireName()));
        $message = new FuncCall(new Name('sprintf'), [new Arg(new String_($format)), new Arg($this->printable($parameter, $property->type(), $types))]);
        $throw = new Expression(new Throw_(new New_(new FullyQualified('InvalidArgumentException'), [new Arg($message)])));

        return new If_($condition, ['stmts' => [$throw]]);
    }

    /**
     * A native enum case is not a string; its backing value is. Null reads as `null`, apart from a quoted value.
     */
    private function printable(Variable $parameter, TypeModel $type, TypeRenderer $types): Expr
    {
        $inner = $type instanceof NullableType ? $type->inner() : $type;
        $value = $inner instanceof EnumType && $types->nativeEnums() ? new PropertyFetch($parameter, 'value') : $parameter;
        if (!$type instanceof NullableType) {
            return $value;
        }

        $quoted = new Concat(new Concat(new String_('"'), $value), new String_('"'));

        return new Ternary(new Identical($parameter, new ConstFetch(new Name('null'))), new String_('null'), $quoted);
    }

    /**
     * @return list<string>
     */
    private function deprecation(DocModel $doc): array
    {
        return $doc->isDeprecated() ? ['@deprecated'] : [];
    }

    private function fetch(string $property): PropertyFetch
    {
        return new PropertyFetch(new Variable('this'), $property);
    }

    private function document(Node $node, ?string $doc): void
    {
        if ($doc !== null) {
            $node->setDocComment(new Doc($doc));
        }
    }

    /**
     * Enum values become `Name::CASE`, a constant expression on every target; anything else a literal.
     *
     * @param JsonValue $value
     */
    private function defaultValue($value, TypeModel $type, TypeRenderer $types): Expr
    {
        $type = $type instanceof NullableType ? $type->inner() : $type;
        if ($type instanceof EnumType) {
            $case = $type->caseFor($value);
            if ($case !== null) {
                return new ClassConstFetch($types->nameOf($type->className()), $case);
            }
        }

        if ($type instanceof ListType && is_array($value) && Json::isList($value)) {
            $items = [];
            foreach ($value as $item) {
                $items[] = new ArrayItem($this->defaultValue(Json::value($item), $type->item(), $types));
            }

            return new Array_($items);
        }

        return ReadableLiteral::of($this->factory->val($value));
    }
}
