<?php

declare(strict_types=1);

namespace MSSTC4PHP\DtoGenerator\Infrastructure\Emitter;

use LogicException;
use MSSTC4PHP\DtoGenerator\Application\Port\CodeEmitter;
use MSSTC4PHP\DtoGenerator\Domain\Model\ClassKind;
use MSSTC4PHP\DtoGenerator\Domain\Model\ClassModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\ClassName;
use MSSTC4PHP\DtoGenerator\Domain\Model\DiscriminatorModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\DocModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\Identifier;
use MSSTC4PHP\DtoGenerator\Domain\Model\PropertyModel;
use MSSTC4PHP\DtoGenerator\Domain\Shared\DefaultValue;
use MSSTC4PHP\DtoGenerator\Domain\Target\ClassForm;
use MSSTC4PHP\DtoGenerator\Domain\Target\TargetProfile;
use MSSTC4PHP\DtoGenerator\Domain\Target\WitherStyle;
use PhpParser\BuilderFactory;
use PhpParser\Comment;
use PhpParser\Comment\Doc;
use PhpParser\Modifiers;
use PhpParser\Node;
use PhpParser\Node\Arg;
use PhpParser\Node\ArrayItem;
use PhpParser\Node\DeclareItem;
use PhpParser\Node\Expr\Array_;
use PhpParser\Node\Expr\Assign;
use PhpParser\Node\Expr\Clone_;
use PhpParser\Node\Expr\FuncCall;
use PhpParser\Node\Expr\New_;
use PhpParser\Node\Expr\PropertyFetch;
use PhpParser\Node\Expr\Variable;
use PhpParser\Node\Name;
use PhpParser\Node\Param;
use PhpParser\Node\Scalar\Int_;
use PhpParser\Node\Scalar\String_;
use PhpParser\Node\Stmt;
use PhpParser\Node\Stmt\ClassMethod;
use PhpParser\Node\Stmt\Declare_;
use PhpParser\Node\Stmt\Expression;
use PhpParser\Node\Stmt\Nop;
use PhpParser\Node\Stmt\Property;
use PhpParser\Node\Stmt\Return_;
use PhpParser\PhpVersion as ParserPhpVersion;

/**
 * Renders one IR class as a PHP file in the shape the target dictates (spec §6.2).
 */
final class PhpParserEmitter implements CodeEmitter
{
    private const HEADER = '// @generated by msstc4php/dto-generator — DO NOT EDIT';

    private BuilderFactory $factory;

    public function __construct()
    {
        $this->factory = new BuilderFactory();
    }

    public function emit(ClassModel $class, TargetProfile $target): string
    {
        $this->assertSupported($class);
        $form = $target->classFormFor($class->mutability());
        $types = new TypeRenderer($class->name()->namespace(), $target);

        $members = [];
        if (!$form->isPromoted()) {
            foreach ($class->properties() as $property) {
                $members[] = $this->declaration($property, $form, $types);
            }
        }

        if ($class->properties() !== []) {
            $members[] = $this->constructor($class, $form, $types);
        }

        foreach ($class->properties() as $property) {
            array_push($members, ...$this->accessors($class, $property, $form, $types));
        }

        $node = $this->factory->class($class->name()->shortName())->addStmts($members)->getNode();
        $node->flags |= $this->modifiers($class->kind(), $form);
        $this->document($node, DocBlock::render($class->doc()->description(), $this->deprecation($class->doc())));

        $header = new Nop();
        $header->setAttribute('comments', [new Comment(self::HEADER)]);

        $statements = [$header, new Declare_([new DeclareItem('strict_types', new Int_(1))])];
        $namespace = $class->name()->namespace();
        $statements[] = $namespace === '' ? $node : $this->factory->namespace($namespace)->addStmt($node)->getNode();

        $printer = new GeneratedCodePrinter([
            'phpVersion' => ParserPhpVersion::fromComponents($target->php()->major(), $target->php()->minor()),
            'shortArraySyntax' => true,
        ]);

        return $printer->prettyPrintFile($statements) . "\n";
    }

    private function assertSupported(ClassModel $class): void
    {
        $fqcn = $class->name()->fqcn();
        if ($class->parent() instanceof ClassName) {
            throw new LogicException(sprintf('%s extends a class; inheritance is emitted from stage 4.', $fqcn));
        }

        if ($class->discriminator() instanceof DiscriminatorModel) {
            throw new LogicException(sprintf('%s has a discriminator; discriminators are emitted from stage 4.', $fqcn));
        }

        $attributes = $class->attributes() !== [];
        foreach ($class->properties() as $property) {
            $attributes = $attributes || $property->attributes() !== [];
        }

        if ($attributes) {
            throw new LogicException(sprintf('%s has attributes; attributes are emitted from stage 5.', $fqcn));
        }
    }

    private function modifiers(ClassKind $kind, ClassForm $form): int
    {
        $flags = $form->isReadonlyClass() ? Modifiers::READONLY : 0;
        if ($kind->isAbstract()) {
            return $flags | Modifiers::ABSTRACT;
        }

        return $kind->equals(ClassKind::from(ClassKind::FINAL)) ? $flags | Modifiers::FINAL : $flags;
    }

    private function declaration(PropertyModel $property, ClassForm $form, TypeRenderer $types): Property
    {
        $builder = $this->factory->property($property->name());
        if ($form->hasPublicProperties()) {
            $builder->makePublic();
        } else {
            $builder->makePrivate();
        }

        if ($form->hasReadonlyProperties()) {
            $builder->makeReadonly();
        }

        $type = $types->nativeNode($property->type());
        if ($type instanceof Node) {
            $builder->setType($type);
        }

        $node = $builder->getNode();
        $this->document($node, $this->propertyDoc($property, $types));

        return $node;
    }

    private function constructor(ClassModel $class, ClassForm $form, TypeRenderer $types): ClassMethod
    {
        $params = [];
        $tags = [];
        $body = [];
        foreach ($this->constructorOrder($class) as $property) {
            $param = $this->param($property, $types, $property->default());
            if ($form->isPromoted()) {
                $param->flags = ($form->hasPublicProperties() ? Modifiers::PUBLIC : Modifiers::PRIVATE)
                    | ($form->hasReadonlyProperties() ? Modifiers::READONLY : 0);
                $this->document($param, $this->propertyDoc($property, $types));
            } else {
                $tags = array_merge($tags, $this->paramTag($property, $types));
                $body[] = new Expression(new Assign($this->fetch($property->name()), new Variable($property->name())));
            }

            $params[] = $param;
        }

        $node = $this->factory->method('__construct')->makePublic()->addParams($params)->addStmts($body)->getNode();
        $this->document($node, DocBlock::render(null, $tags));

        return $node;
    }

    /**
     * @return list<ClassMethod>
     */
    private function accessors(ClassModel $class, PropertyModel $property, ClassForm $form, TypeRenderer $types): array
    {
        $name = $property->name();
        $suffix = Identifier::asciiUpperFirst($name);
        $deprecation = $this->deprecation($property->doc());
        $methods = [];

        if ($form->hasGetters()) {
            $getter = $this->factory->method('get' . $suffix)->makePublic()->addStmt(new Return_($this->fetch($name)));
            $type = $types->nativeNode($property->type());
            if ($type instanceof Node) {
                $getter->setReturnType($type);
            }

            $node = $getter->getNode();
            $returnTag = $types->needsDoc($property->type()) ? ['@return ' . $types->doc($property->type())] : [];
            $this->document($node, DocBlock::render(null, array_merge($returnTag, $deprecation)));
            $methods[] = $node;
        }

        if ($form->hasSetters()) {
            $methods[] = $this->mutator('set' . $suffix, $property, $types, [
                new Expression(new Assign($this->fetch($name), new Variable($name))),
                new Return_(new Variable('this')),
            ]);
        }

        if (!$form->withers()->isNone()) {
            $methods[] = $this->mutator('with' . $suffix, $property, $types, $this->witherBody($class, $property, $form->withers()));
        }

        return $methods;
    }

    /**
     * @param list<Stmt> $body
     */
    private function mutator(string $method, PropertyModel $property, TypeRenderer $types, array $body): ClassMethod
    {
        $node = $this->factory->method($method)
            ->makePublic()
            ->addParam($this->param($property, $types, null))
            ->setReturnType('self')
            ->addStmts($body)
            ->getNode()
        ;
        $this->document($node, DocBlock::render(null, array_merge($this->paramTag($property, $types), $this->deprecation($property->doc()))));

        return $node;
    }

    /**
     * @return list<Stmt>
     */
    private function witherBody(ClassModel $class, PropertyModel $property, WitherStyle $style): array
    {
        $name = $property->name();
        if ($style->equals(WitherStyle::from(WitherStyle::CLONE_WITH))) {
            $changes = new Array_([new ArrayItem(new Variable($name), new String_($name))], ['kind' => Array_::KIND_SHORT]);

            return [new Return_(new FuncCall(new Name('clone'), [new Arg(new Variable('this')), new Arg($changes)]))];
        }

        if ($style->equals(WitherStyle::from(WitherStyle::NEW_SELF))) {
            $args = [];
            foreach ($this->constructorOrder($class) as $other) {
                $args[] = new Arg($other === $property ? new Variable($name) : $this->fetch($other->name()));
            }

            return [new Return_(new New_(new Name('self'), $args))];
        }

        // The copy must not shadow the parameter, which carries the property's own name.
        $copy = $name === 'clone' ? 'copy' : 'clone';

        return [
            new Expression(new Assign(new Variable($copy), new Clone_(new Variable('this')))),
            new Expression(new Assign(new PropertyFetch(new Variable($copy), $name), new Variable($name))),
            new Return_(new Variable($copy)),
        ];
    }

    private function param(PropertyModel $property, TypeRenderer $types, ?DefaultValue $default): Param
    {
        $builder = $this->factory->param($property->name());
        $type = $types->nativeNode($property->type());
        if ($type instanceof Node) {
            $builder->setType($type);
        }

        if ($default instanceof DefaultValue) {
            $builder->setDefault($default->value());
        }

        return $builder->getNode();
    }

    /**
     * @return list<string>
     */
    private function paramTag(PropertyModel $property, TypeRenderer $types): array
    {
        return $types->needsDoc($property->type()) ? ['@param ' . $types->doc($property->type()) . ' $' . $property->name()] : [];
    }

    private function propertyDoc(PropertyModel $property, TypeRenderer $types): ?string
    {
        $var = $types->needsDoc($property->type()) ? ['@var ' . $types->doc($property->type())] : [];

        return DocBlock::render($property->doc()->description(), array_merge($var, $this->deprecation($property->doc())));
    }

    /**
     * Required parameters first (spec §5.2): an optional one before a required one is deprecated since PHP 8.0.
     *
     * @return list<PropertyModel>
     */
    private function constructorOrder(ClassModel $class): array
    {
        $required = [];
        $optional = [];
        foreach ($class->properties() as $property) {
            if ($property->isRequired()) {
                $required[] = $property;
            } else {
                $optional[] = $property;
            }
        }

        return array_merge($required, $optional);
    }

    /**
     * @return list<string>
     */
    private function deprecation(DocModel $doc): array
    {
        return $doc->isDeprecated() ? ['@deprecated'] : [];
    }

    private function fetch(string $property): PropertyFetch
    {
        return new PropertyFetch(new Variable('this'), $property);
    }

    private function document(Node $node, ?string $doc): void
    {
        if ($doc !== null) {
            $node->setDocComment(new Doc($doc));
        }
    }
}
