<?php

declare(strict_types=1);

namespace MSSTC4PHP\DtoGenerator\Infrastructure\Writer;

use MSSTC4PHP\DtoGenerator\Application\Port\FileWriter;
use MSSTC4PHP\DtoGenerator\Application\Port\WriteFailed;
use MSSTC4PHP\DtoGenerator\Application\Service\Generate\FileChange;
use MSSTC4PHP\DtoGenerator\Application\Service\Generate\WritePlan;

/**
 * Writes each output directory atomically per file and records what it owns in a manifest (spec §9.1), so stale
 * files can be removed and hand-written files are never overwritten.
 */
final class FilesystemWriter implements FileWriter
{
    private const MANIFEST = '.dto-generator.manifest.json';

    private const MARKER = '@generated by msstc4php/dto-generator';

    public function plan(array $outputDirs, array $files): WritePlan
    {
        $byDirectory = [];
        foreach ($outputDirs as $outputDir) {
            $byDirectory[rtrim($outputDir, '/')] = [];
        }

        foreach ($files as $file) {
            $byDirectory[rtrim($file->outputDir(), '/')][$file->relativePath()] = $file->contents();
        }

        $changes = [];
        $conflicts = [];
        $manifests = [];
        foreach ($byDirectory as $directory => $contents) {
            ksort($contents, SORT_STRING);
            $manifestPath = $directory . '/' . self::MANIFEST;
            $previous = $this->readManifest($manifestPath);
            $owned = [];
            foreach ($contents as $relativePath => $content) {
                $path = $directory . '/' . $relativePath;
                $current = is_file($path) ? (string) file_get_contents($path) : null;
                $owned[$relativePath] = hash('sha256', $content);
                if ($current === null) {
                    $changes[] = FileChange::create($path, $content);
                } elseif ($current === $content) {
                    $changes[] = FileChange::unchanged($path);
                } elseif ($this->isGenerated($current)) {
                    $changes[] = FileChange::update($path, $content);
                } else {
                    $conflicts[$path] = 'The file exists but was not generated by dto-generator (no "@generated" header); remove it or choose another outputDir.';
                }
            }

            foreach ($previous as $relativePath => $hash) {
                $path = $directory . '/' . $relativePath;
                if (isset($owned[$relativePath]) || !is_file($path)) {
                    continue;
                }

                if ($this->isGenerated((string) file_get_contents($path))) {
                    $changes[] = FileChange::delete($path);
                } else {
                    $conflicts[$path] = 'The file is no longer generated, but its "@generated" header was removed, so it is kept; delete it by hand.';
                    $owned[$relativePath] = $hash;
                }
            }

            // An output directory that never received a file gets no manifest either.
            if ($owned === [] && !is_file($manifestPath)) {
                continue;
            }

            ksort($owned, SORT_STRING);
            $manifest = json_encode(['generator' => 'msstc4php/dto-generator', 'files' => $owned], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";
            if (!is_file($manifestPath) || file_get_contents($manifestPath) !== $manifest) {
                $manifests[$manifestPath] = $manifest;
            }
        }

        return new WritePlan($changes, $conflicts, $manifests);
    }

    public function apply(WritePlan $plan): void
    {
        foreach ($plan->changes() as $change) {
            $contents = $change->contents();
            if ($change->kind() === FileChange::DELETE) {
                $this->quietly(static fn (): bool => unlink($change->path()), $change->path(), 'delete');
            } elseif ($contents !== null) {
                $this->writeAtomically($change->path(), $contents);
            }
        }

        foreach ($plan->manifests() as $path => $contents) {
            $this->writeAtomically($path, $contents);
        }
    }

    /**
     * @return array<string, string> relative path → sha256
     */
    private function readManifest(string $path): array
    {
        $decoded = is_file($path) ? json_decode((string) file_get_contents($path), true) : null;
        $files = is_array($decoded) ? ($decoded['files'] ?? null) : null;
        if (!is_array($files)) {
            return [];
        }

        $manifest = [];
        foreach ($files as $relativePath => $hash) {
            if (is_string($hash)) {
                $manifest[(string) $relativePath] = $hash;
            }
        }

        return $manifest;
    }

    private function isGenerated(string $contents): bool
    {
        return strpos($contents, self::MARKER) !== false;
    }

    private function writeAtomically(string $path, string $contents): void
    {
        $directory = dirname($path);
        if (!is_dir($directory)) {
            $this->quietly(static fn (): bool => mkdir($directory, 0777, true), $path, 'write');
        }

        // The temporary file lives next to the target, so rename() never crosses a filesystem.
        $temporary = $directory . '/.' . basename($path) . '.' . bin2hex(random_bytes(6)) . '.tmp';
        $this->quietly(static fn (): bool => file_put_contents($temporary, $contents) === strlen($contents), $path, 'write');
        $this->quietly(static fn (): bool => chmod($temporary, 0644) && rename($temporary, $path), $path, 'write');
    }

    /**
     * Runs a filesystem call without letting its warning escape, and turns failure into WriteFailed.
     *
     * @param callable(): bool $operation
     */
    private function quietly(callable $operation, string $path, string $action): void
    {
        set_error_handler(static fn (): bool => true);

        try {
            $succeeded = $operation();
        } finally {
            restore_error_handler();
        }

        if (!$succeeded) {
            throw WriteFailed::at($path, $action);
        }
    }
}
