<?php

declare(strict_types=1);

namespace MSSTC4PHP\DtoGenerator\Infrastructure\Writer;

use MSSTC4PHP\DtoGenerator\Application\Port\FileWriter;
use MSSTC4PHP\DtoGenerator\Application\Port\WriteFailed;
use MSSTC4PHP\DtoGenerator\Application\Service\Generate\FileChange;
use MSSTC4PHP\DtoGenerator\Application\Service\Generate\WritePlan;

/**
 * Writes each output directory atomically per file and records what it owns in a manifest (spec §9.1), so stale
 * files can be removed and hand-written files are never overwritten. The output directories stay locked from
 * plan() to apply() or release().
 */
final class FilesystemWriter implements FileWriter
{
    private const MARKER = '@generated by msstc4php/dto-generator';

    private ManifestCodec $codec;

    private DirectoryLocks $locks;

    public function __construct()
    {
        $this->codec = new ManifestCodec();
        $this->locks = new DirectoryLocks();
    }

    public function plan(array $outputDirs, array $files): WritePlan
    {
        $byDirectory = [];
        foreach ($outputDirs as $outputDir) {
            $byDirectory[rtrim($outputDir, '/')] = [];
        }

        $conflicts = [];
        $claimed = [];
        foreach ($files as $file) {
            $directory = rtrim($file->outputDir(), '/');
            $key = $directory . '/' . strtolower($file->relativePath());
            if (isset($claimed[$key])) {
                $conflicts[$directory . '/' . $file->relativePath()] = 'Another generated class already maps to this file (letter case ignored); give the sources different outputDirs or the classes different names.';

                continue;
            }

            $claimed[$key] = true;
            $byDirectory[$directory][$file->relativePath()] = $file->contents();
        }

        // PHP 7.4 throws on a NUL byte in a path, PHP 8 fails quietly; neither can ever write there.
        foreach (array_keys($byDirectory) as $directory) {
            if (strpos($directory, "\0") !== false) {
                $conflicts[$directory] = 'The output directory path contains a NUL byte.';
                unset($byDirectory[$directory]);
            }
        }

        $this->locks->release();
        $this->locks->acquire(array_keys($byDirectory));

        $plans = [new WritePlan([], $conflicts, [])];
        foreach ($byDirectory as $directory => $contents) {
            $plans[] = $this->planDirectory($directory, $contents);
        }

        return $this->merge($plans);
    }

    public function apply(WritePlan $plan): void
    {
        try {
            // Recorded first, so a run that stops halfway still knows every file it may have written or not yet deleted.
            foreach ($plan->manifests() as $path => $contents) {
                $this->writeAtomically($path, $plan->interimManifests()[$path] ?? $contents);
            }

            // Deletions first: on a case-insensitive filesystem a class renamed from Foo to FOO deletes and writes one file.
            foreach ($plan->changes() as $change) {
                if ($change->kind() === FileChange::DELETE) {
                    $this->quietly(static fn (): bool => unlink($change->path()), $change->path(), 'delete');
                }
            }

            foreach ($plan->changes() as $change) {
                $contents = $change->contents();
                if ($contents !== null) {
                    $this->writeAtomically($change->path(), $contents);
                }
            }

            foreach ($plan->manifests() as $path => $contents) {
                $this->writeAtomically($path, $contents);
            }
        } finally {
            $this->release();
        }
    }

    public function release(): void
    {
        $this->locks->release();
    }

    /**
     * @param array<string, string> $contents relative path → contents
     */
    private function planDirectory(string $directory, array $contents): WritePlan
    {
        ksort($contents, SORT_STRING);
        $manifestPath = $directory . '/' . ManifestCodec::FILE;
        $manifestText = file_exists($manifestPath) ? $this->read($manifestPath) : '';
        $previous = $manifestText === '' ? [] : $this->codec->decode((string) $manifestText);
        if ($previous === null) {
            return new WritePlan([], [$manifestPath => 'The manifest is not a valid dto-generator manifest, so stale files cannot be found; fix it or delete it.'], []);
        }

        $changes = [];
        $conflicts = [];
        $owned = [];
        foreach ($contents as $relativePath => $content) {
            $path = $directory . '/' . $relativePath;
            $owned[$relativePath] = hash('sha256', $content);
            $change = $this->change($path, $content);
            if ($change instanceof FileChange) {
                $changes[] = $change;
            } else {
                $conflicts[$path] = $change;
            }
        }

        $deleted = [];
        foreach ($previous as $relativePath => $hash) {
            $path = $directory . '/' . $relativePath;
            if (isset($owned[$relativePath]) || !is_file($path)) {
                continue;
            }

            $current = $this->read($path);
            if ($current !== null && $this->isGenerated($current)) {
                $changes[] = FileChange::delete($path);
                $deleted[$relativePath] = $hash;
            } else {
                $conflicts[$path] = $current === null
                    ? 'The file cannot be read, so it is not deleted.'
                    : 'The file is no longer generated, but its "@generated" header was removed, so it is kept; delete it by hand.';
                $owned[$relativePath] = $hash;
            }
        }

        // An output directory that never received a file gets no manifest either.
        if ($owned === [] && $manifestText === '') {
            return new WritePlan($changes, $conflicts, []);
        }

        $manifest = $this->codec->encode($owned);
        $manifests = $manifestText !== null && $this->sameText($manifestText, $manifest) ? [] : [$manifestPath => $manifest];
        $interim = $deleted === [] ? [] : [$manifestPath => $this->codec->encode($owned + $deleted)];

        return new WritePlan($changes, $conflicts, $manifests, $interim, $manifestText === '' ? [$manifestPath] : []);
    }

    /**
     * @return FileChange|string the change, or why the file must not be touched
     */
    private function change(string $path, string $content)
    {
        if (!file_exists($path)) {
            return FileChange::create($path, $content);
        }

        $current = $this->read($path);
        if ($current === null) {
            return 'The file cannot be read, so it is not overwritten.';
        }

        if ($this->sameText($current, $content)) {
            return FileChange::unchanged($path);
        }

        return $this->isGenerated($current)
            ? FileChange::update($path, $content)
            : 'The file exists but was not generated by dto-generator (no "@generated" header); remove it or choose another outputDir.';
    }

    /**
     * Git may check generated files out with CRLF on Windows; the content is still the same.
     */
    private function sameText(string $current, string $generated): bool
    {
        return str_replace("\r\n", "\n", $current) === $generated;
    }

    /**
     * @param list<WritePlan> $plans
     */
    private function merge(array $plans): WritePlan
    {
        $changes = [];
        $conflicts = [];
        $manifests = [];
        $interim = [];
        $new = [];
        foreach ($plans as $plan) {
            $changes = array_merge($changes, $plan->changes());
            $conflicts += $plan->conflicts();
            $manifests += $plan->manifests();
            $interim += $plan->interimManifests();
            foreach (array_keys($plan->manifests()) as $path) {
                if ($plan->isNewManifest($path)) {
                    $new[] = $path;
                }
            }
        }

        return new WritePlan($changes, $conflicts, $manifests, $interim, $new);
    }

    private function read(string $path): ?string
    {
        $contents = $this->silently(static fn () => is_readable($path) ? file_get_contents($path) : false);

        return is_string($contents) ? $contents : null;
    }

    private function isGenerated(string $contents): bool
    {
        return strpos($contents, self::MARKER) !== false;
    }

    private function writeAtomically(string $path, string $contents): void
    {
        $directory = dirname($path);
        if (!is_dir($directory)) {
            $this->quietly(static fn (): bool => mkdir($directory, 0777, true), $path, 'write');
        }

        $mode = $this->modeFor($path);
        $temporary = $this->temporaryPath($path);

        try {
            $this->quietly(static fn (): bool => file_put_contents($temporary, $contents) === strlen($contents), $path, 'write');
            $this->quietly(static fn (): bool => rename($temporary, $path), $path, 'write');
        } catch (WriteFailed $exception) {
            $this->silently(static fn (): bool => !file_exists($temporary) || unlink($temporary));

            throw $exception;
        }

        // Best effort: some filesystems (CIFS, vboxsf) refuse chmod, and the content is what matters.
        $this->silently(static fn (): bool => chmod($path, $mode));
    }

    /**
     * An updated file keeps its permissions; a new one gets what the umask allows.
     */
    private function modeFor(string $path): int
    {
        $permissions = is_file($path) ? $this->silently(static fn () => fileperms($path)) : false;

        return is_int($permissions) ? $permissions & 0777 : 0666 & ~umask();
    }

    /**
     * Next to the target, so rename() never crosses a filesystem; hidden and random, so it never clashes.
     */
    private function temporaryPath(string $path): string
    {
        return dirname($path) . '/.' . basename($path) . '.' . bin2hex(random_bytes(6)) . '.tmp';
    }

    /**
     * @param callable(): bool $operation
     */
    private function quietly(callable $operation, string $path, string $action): void
    {
        if (!$this->silently($operation)) {
            throw WriteFailed::at($path, $action);
        }
    }

    /**
     * Runs a filesystem call without letting its warning escape.
     *
     * @template T
     *
     * @param callable(): T $operation
     *
     * @return T
     */
    private function silently(callable $operation)
    {
        set_error_handler(static fn (): bool => true);

        try {
            return $operation();
        } finally {
            restore_error_handler();
        }
    }
}
