<?php

declare(strict_types=1);

namespace MSSTC4PHP\DtoGenerator\Infrastructure\Writer;

use MSSTC4PHP\DtoGenerator\Application\Port\FileWriter;
use MSSTC4PHP\DtoGenerator\Application\Port\WriteFailed;
use MSSTC4PHP\DtoGenerator\Application\Service\Generate\FileChange;
use MSSTC4PHP\DtoGenerator\Application\Service\Generate\GeneratedFile;
use MSSTC4PHP\DtoGenerator\Application\Service\Generate\WritePlan;

/**
 * Writes each output directory atomically per file and records what it owns in a manifest (spec §9.1), so stale
 * files can be removed and hand-written files are never overwritten. A run holds a lock per output directory from
 * plan() to apply(), so concurrent runs cannot interleave.
 */
final class FilesystemWriter implements FileWriter
{
    private const MANIFEST = '.dto-generator.manifest.json';

    private const MARKER = '@generated by msstc4php/dto-generator';

    /** @var array<string, resource> lock path → open handle */
    private array $locks = [];

    public function __destruct()
    {
        $this->releaseLocks();
    }

    /**
     * Outside the output directory, so the lock is never mistaken for output.
     */
    public static function lockPath(string $outputDir): string
    {
        return sys_get_temp_dir() . '/dto-generator-' . sha1(rtrim($outputDir, '/')) . '.lock';
    }

    public function plan(array $outputDirs, array $files): WritePlan
    {
        $byDirectory = [];
        foreach ($outputDirs as $outputDir) {
            $byDirectory[rtrim($outputDir, '/')] = [];
        }

        $conflicts = [];
        $claimed = [];
        foreach ($files as $file) {
            $directory = rtrim($file->outputDir(), '/');
            $key = $directory . '/' . strtolower($file->relativePath());
            if (isset($claimed[$key])) {
                $conflicts[$directory . '/' . $file->relativePath()] = 'Another generated class already maps to this file (letter case ignored); give the sources different outputDirs or the classes different names.';

                continue;
            }

            $claimed[$key] = true;
            $byDirectory[$directory][$file->relativePath()] = $file->contents();
        }

        $changes = [];
        $manifests = [];
        $interim = [];
        foreach ($byDirectory as $directory => $contents) {
            // PHP 7.4 throws on a NUL byte in a path, PHP 8 fails quietly; neither can ever write there.
            if (strpos($directory, "\0") !== false) {
                $conflicts[$directory] = 'The output directory path contains a NUL byte.';

                continue;
            }

            $this->lock($directory);
            ksort($contents, SORT_STRING);
            $manifestPath = $directory . '/' . self::MANIFEST;
            $previous = $this->readManifest($manifestPath);
            if ($previous === null) {
                $conflicts[$manifestPath] = 'The manifest is not a valid dto-generator manifest, so stale files cannot be found; fix it or delete it.';

                continue;
            }

            $owned = [];
            foreach ($contents as $relativePath => $content) {
                $path = $directory . '/' . $relativePath;
                $owned[$relativePath] = hash('sha256', $content);
                $change = $this->change($path, $content);
                if ($change instanceof FileChange) {
                    $changes[] = $change;
                } else {
                    $conflicts[$path] = $this->conflict($path);
                }
            }

            $deleted = [];
            foreach ($previous as $relativePath => $hash) {
                $path = $directory . '/' . $relativePath;
                if (isset($owned[$relativePath]) || !is_file($path)) {
                    continue;
                }

                $current = $this->read($path);
                if ($current !== null && $this->isGenerated($current)) {
                    $changes[] = FileChange::delete($path);
                    $deleted[$relativePath] = $hash;
                } else {
                    $conflicts[$path] = $current === null
                        ? 'The file cannot be read, so it is not deleted.'
                        : 'The file is no longer generated, but its "@generated" header was removed, so it is kept; delete it by hand.';
                    $owned[$relativePath] = $hash;
                }
            }

            // An output directory that never received a file gets no manifest either.
            if ($owned === [] && !is_file($manifestPath)) {
                continue;
            }

            $manifest = $this->encodeManifest($owned);
            if ($this->read($manifestPath) !== $manifest) {
                $manifests[$manifestPath] = $manifest;
            }

            if ($deleted !== []) {
                $interim[$manifestPath] = $this->encodeManifest($owned + $deleted);
            }
        }

        return new WritePlan($changes, $conflicts, $manifests, $interim);
    }

    public function apply(WritePlan $plan): void
    {
        try {
            // Recorded first, so a run that stops halfway still knows every file it may have written or not yet deleted.
            foreach ($plan->manifests() as $path => $contents) {
                $this->writeAtomically($path, $plan->interimManifests()[$path] ?? $contents);
            }

            foreach ($plan->changes() as $change) {
                $contents = $change->contents();
                if ($change->kind() === FileChange::DELETE) {
                    $this->quietly(static fn (): bool => unlink($change->path()), $change->path(), 'delete');
                } elseif ($contents !== null) {
                    $this->writeAtomically($change->path(), $contents);
                }
            }

            foreach ($plan->manifests() as $path => $contents) {
                $this->writeAtomically($path, $contents);
            }
        } finally {
            $this->releaseLocks();
        }
    }

    private function change(string $path, string $content): ?FileChange
    {
        if (!file_exists($path)) {
            return FileChange::create($path, $content);
        }

        $current = $this->read($path);
        if ($current === null) {
            return null;
        }

        // Git may check generated files out with CRLF on Windows; the content is still the same.
        if (str_replace("\r\n", "\n", $current) === $content) {
            return FileChange::unchanged($path);
        }

        return $this->isGenerated($current) ? FileChange::update($path, $content) : null;
    }

    private function conflict(string $path): string
    {
        return $this->read($path) === null
            ? 'The file cannot be read, so it is not overwritten.'
            : 'The file exists but was not generated by dto-generator (no "@generated" header); remove it or choose another outputDir.';
    }

    /**
     * @param array<string, string> $owned
     */
    private function encodeManifest(array $owned): string
    {
        ksort($owned, SORT_STRING);

        return json_encode(['generator' => 'msstc4php/dto-generator', 'files' => $owned], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";
    }

    /**
     * @return array<string, string>|null relative path → sha256; empty when there is no manifest, null when it is corrupt
     */
    private function readManifest(string $path): ?array
    {
        if (!file_exists($path)) {
            return [];
        }

        $text = $this->read($path);
        $decoded = $text === null ? null : json_decode($text, true);
        $files = is_array($decoded) ? ($decoded['files'] ?? null) : null;
        if (!is_array($files)) {
            return null;
        }

        $manifest = [];
        foreach ($files as $relativePath => $hash) {
            // A manifest is committed and can be edited in a pull request; it must never point outside its directory.
            if (!is_string($relativePath) || !is_string($hash) || !GeneratedFile::isSafeRelativePath($relativePath)) {
                return null;
            }

            $manifest[$relativePath] = $hash;
        }

        return $manifest;
    }

    private function read(string $path): ?string
    {
        set_error_handler(static fn (): bool => true);
        $contents = is_readable($path) ? file_get_contents($path) : false;
        restore_error_handler();

        return $contents === false ? null : $contents;
    }

    private function isGenerated(string $contents): bool
    {
        return strpos($contents, self::MARKER) !== false;
    }

    private function writeAtomically(string $path, string $contents): void
    {
        $directory = dirname($path);
        if (!is_dir($directory)) {
            $this->quietly(static fn (): bool => mkdir($directory, 0777, true), $path, 'write');
        }

        // An updated file keeps the permissions its owner gave it.
        $mode = is_file($path) ? fileperms($path) & 0777 : 0644;
        $temporary = $this->temporaryPath($path);

        try {
            $this->quietly(static fn (): bool => file_put_contents($temporary, $contents) === strlen($contents), $path, 'write');
            $this->quietly(static fn (): bool => chmod($temporary, $mode) && rename($temporary, $path), $path, 'write');
        } catch (WriteFailed $exception) {
            $this->quietly(static fn (): bool => !file_exists($temporary) || unlink($temporary), $temporary, 'delete');

            throw $exception;
        }
    }

    /**
     * Next to the target, so rename() never crosses a filesystem; hidden and random, so it never clashes.
     */
    private function temporaryPath(string $path): string
    {
        return dirname($path) . '/.' . basename($path) . '.' . bin2hex(random_bytes(6)) . '.tmp';
    }

    /**
     * Runs a filesystem call without letting its warning escape, and turns failure into WriteFailed.
     *
     * @param callable(): bool $operation
     */
    private function quietly(callable $operation, string $path, string $action): void
    {
        set_error_handler(static fn (): bool => true);

        try {
            $succeeded = $operation();
        } finally {
            restore_error_handler();
        }

        if (!$succeeded) {
            throw WriteFailed::at($path, $action);
        }
    }

    private function lock(string $directory): void
    {
        $path = self::lockPath($directory);
        if (isset($this->locks[$path])) {
            return;
        }

        $handle = fopen($path, 'c');
        if ($handle !== false && flock($handle, LOCK_EX)) {
            $this->locks[$path] = $handle;
        }
    }

    private function releaseLocks(): void
    {
        foreach ($this->locks as $handle) {
            flock($handle, LOCK_UN);
            fclose($handle);
        }

        $this->locks = [];
    }
}
