<?php

declare(strict_types=1);

namespace MSSTC4PHP\DtoGenerator\Tests\Unit\Infrastructure\Emitter;

use LogicException;
use MSSTC4PHP\DtoGenerator\Domain\Model\AttributeModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\ClassKind;
use MSSTC4PHP\DtoGenerator\Domain\Model\ClassModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\ClassName;
use MSSTC4PHP\DtoGenerator\Domain\Model\DiscriminatorModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\DocModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\EnumBacking;
use MSSTC4PHP\DtoGenerator\Domain\Model\EnumCase;
use MSSTC4PHP\DtoGenerator\Domain\Model\EnumModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\EnumType;
use MSSTC4PHP\DtoGenerator\Domain\Model\ListType;
use MSSTC4PHP\DtoGenerator\Domain\Model\MixedType;
use MSSTC4PHP\DtoGenerator\Domain\Model\NullableType;
use MSSTC4PHP\DtoGenerator\Domain\Model\ScalarType;
use MSSTC4PHP\DtoGenerator\Domain\Schema\SchemaLocation;
use MSSTC4PHP\DtoGenerator\Domain\Shared\DefaultValue;
use MSSTC4PHP\DtoGenerator\Domain\Target\AccessorStyle;
use MSSTC4PHP\DtoGenerator\Domain\Target\Mutability;
use MSSTC4PHP\DtoGenerator\Infrastructure\Emitter\PhpParserEmitter;
use MSSTC4PHP\DtoGenerator\Tests\Support\EmitterFixture;
use PHPUnit\Framework\TestCase;

final class PhpParserEmitterTest extends TestCase
{
    private const HEAD = "<?php\n\n// @generated by msstc4php/dto-generator — DO NOT EDIT\n\ndeclare(strict_types=1);\n\nnamespace App\\Dto;\n\n/**\n * A point.\n */\n";

    public function testEmitsAnImmutableClassForPhp74(): void
    {
        self::assertSame(self::HEAD . <<<'PHP'
            final class Point
            {
                /**
                 * Horizontal.
                 */
                private int $x;

                private ?string $label;

                public function __construct(int $x, ?string $label = null)
                {
                    $this->x = $x;
                    $this->label = $label;
                }

                public function getLabel(): ?string
                {
                    return $this->label;
                }

                public function withLabel(?string $label): self
                {
                    $clone = clone $this;
                    $clone->label = $label;

                    return $clone;
                }

                public function getX(): int
                {
                    return $this->x;
                }

                public function withX(int $x): self
                {
                    $clone = clone $this;
                    $clone->x = $x;

                    return $clone;
                }
            }

            PHP, $this->emit(Mutability::IMMUTABLE, '7.4'));
    }

    public function testEmitsPublicReadonlyPromotedPropertiesForPhp81(): void
    {
        self::assertSame(self::HEAD . <<<'PHP'
            final class Point
            {
                public function __construct(
                    /**
                     * Horizontal.
                     */
                    public readonly int $x,
                    public readonly ?string $label = null,
                ) {
                }

                public function withLabel(?string $label): self
                {
                    return new self($this->x, $label);
                }

                public function withX(int $x): self
                {
                    return new self($x, $this->label);
                }
            }

            PHP, $this->emit(Mutability::IMMUTABLE, '8.1'));
    }

    public function testEmitsAReadonlyClassForPhp82(): void
    {
        $code = $this->emit(Mutability::IMMUTABLE, '8.2');

        self::assertStringContainsString("final readonly class Point\n", $code);
        self::assertStringContainsString("        public int \$x,\n        public ?string \$label = null,\n", $code);
    }

    public function testClonesWithPropertiesOnPhp85(): void
    {
        self::assertStringContainsString("        return clone(\$this, ['x' => \$x]);\n", $this->emit(Mutability::IMMUTABLE, '8.5'));
    }

    public function testEmitsGettersAndSettersForAMutableClass(): void
    {
        $code = $this->emit(Mutability::MUTABLE, '8.5', AccessorStyle::GETTERS);

        self::assertStringContainsString("        private int \$x,\n        private ?string \$label = null,\n", $code);
        self::assertStringContainsString(<<<'PHP'
                public function setLabel(?string $label): self
                {
                    $this->label = $label;

                    return $this;
                }
            PHP, $code);
        self::assertStringNotContainsString('function with', $code);
    }

    public function testEmitsOnlyPublicPropertiesForAMutablePublicClass(): void
    {
        $code = $this->emit(Mutability::MUTABLE, '7.4', AccessorStyle::PUBLIC_PROPERTIES);

        self::assertStringContainsString("    public ?string \$label;\n", $code);
        self::assertStringNotContainsString('function get', $code);
        self::assertStringNotContainsString('function set', $code);
    }

    public function testDocumentsTypesTheTargetCannotDeclare(): void
    {
        $class = EmitterFixture::model('App\Dto\Sample', null, [EmitterFixture::sample()->properties()[3]]);
        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringContainsString("    /**\n     * @var int|string\n     */\n    private \$code;\n", $code);
        self::assertStringContainsString("    /**\n     * @param int|string \$code\n     */\n    public function __construct(\$code)\n", $code);
        self::assertStringContainsString("    /**\n     * @return int|string\n     */\n    public function getCode()\n", $code);
    }

    public function testRenamesTheCloneVariableForAPropertyNamedClone(): void
    {
        $class = EmitterFixture::model('App\Dto\Copy', null, [EmitterFixture::property('clone', ScalarType::int(), true)]);
        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringContainsString("        \$copy = clone \$this;\n        \$copy->clone = \$clone;\n\n        return \$copy;\n", $code);
    }

    public function testMarksDeprecatedPropertiesAndTheirAccessors(): void
    {
        $class = EmitterFixture::model('App\Dto\Old', null, [EmitterFixture::property('id', ScalarType::int(), true, null, null, true)]);
        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertSame(3, substr_count($code, "     * @deprecated\n"));
    }

    public function testEmitsAClassWithoutPropertiesWithoutAConstructor(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::model('App\Dto\Nothing', null, []), EmitterFixture::target('8.2', Mutability::IMMUTABLE));

        self::assertStringEndsWith("final readonly class Nothing\n{\n}\n", $code);
    }

    public function testEmitsAGlobalClassWithoutANamespace(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::model('Point', null, []), EmitterFixture::target('8.2', Mutability::IMMUTABLE));

        self::assertStringNotContainsString('namespace', $code);
        self::assertStringStartsWith("<?php\n\n// @generated by msstc4php/dto-generator — DO NOT EDIT\n\ndeclare(strict_types=1);\n\nfinal readonly class Point\n", $code);
    }

    /**
     * @dataProvider unsupported
     */
    public function testRejectsWhatLaterStagesAdd(ClassModel $class, string $message): void
    {
        $this->expectException(LogicException::class);
        $this->expectExceptionMessage($message);

        (new PhpParserEmitter())->emit($class, EmitterFixture::target('8.2', Mutability::IMMUTABLE));
    }

    /**
     * @return array<string, array{ClassModel, string}>
     */
    public static function unsupported(): array
    {
        $name = ClassName::fromFqcn('App\Dto\Pet');
        $at = new SchemaLocation('/project/api/openapi.yaml', '/components/schemas/Pet');
        $attribute = new AttributeModel(ClassName::fromFqcn('App\Attr\Audited'));
        $immutable = Mutability::from(Mutability::IMMUTABLE);

        return [
            'parent' => [new ClassModel($name, ClassKind::from(ClassKind::FINAL), ClassName::fromFqcn('App\Dto\Animal'), [], $immutable, DocModel::none(), $at), 'App\Dto\Pet extends a class'],
            'discriminator' => [new ClassModel($name, ClassKind::from(ClassKind::ABSTRACT), null, [], $immutable, DocModel::none(), $at, [], new DiscriminatorModel('kind', ['cat' => ClassName::fromFqcn('App\Dto\Cat')])), 'App\Dto\Pet has a discriminator'],
            'class attribute' => [new ClassModel($name, ClassKind::from(ClassKind::FINAL), null, [], $immutable, DocModel::none(), $at, [$attribute]), 'App\Dto\Pet has attributes'],
            'open class with properties' => [new ClassModel($name, ClassKind::from(ClassKind::OPEN), null, [EmitterFixture::property('id', ScalarType::int(), true)], $immutable, DocModel::none(), $at), 'App\Dto\Pet is not final'],
            'base class with properties' => [new ClassModel($name, ClassKind::from(ClassKind::ABSTRACT), null, [EmitterFixture::property('id', ScalarType::int(), true)], $immutable, DocModel::none(), $at), 'App\Dto\Pet is not final'],
            'property attribute' => [EmitterFixture::model('App\Dto\Pet', null, [EmitterFixture::property('id', ScalarType::int(), true)->withAddedAttributes($attribute)]), 'App\Dto\Pet has attributes'],
        ];
    }

    public function testEmitsAbstractAndOpenClasses(): void
    {
        $emitter = new PhpParserEmitter();
        $target = EmitterFixture::target('8.0', Mutability::IMMUTABLE);
        $at = new SchemaLocation('/project/api/openapi.yaml', '/components/schemas/Base');
        $immutable = Mutability::from(Mutability::IMMUTABLE);

        self::assertStringContainsString("\nabstract class Base\n", $emitter->emit(new ClassModel(ClassName::fromFqcn('App\Dto\Base'), ClassKind::from(ClassKind::ABSTRACT), null, [], $immutable, DocModel::none(), $at), $target));
        self::assertStringContainsString("\nclass Base\n", $emitter->emit(new ClassModel(ClassName::fromFqcn('App\Dto\Base'), ClassKind::from(ClassKind::OPEN), null, [], $immutable, DocModel::none(), $at), $target));
    }

    public function testPrintsStringDefaultsWithControlCharactersDoubleQuoted(): void
    {
        $class = EmitterFixture::model('App\Dto\Note', null, [
            EmitterFixture::property('text', new NullableType(ScalarType::string()), false, new DefaultValue("x\n)\n{")),
            EmitterFixture::property('lines', new NullableType(new ListType(ScalarType::string())), false, new DefaultValue(["a\tb", 'plain'])),
            EmitterFixture::property('map', new MixedType(), false, new DefaultValue(["a\nb" => 1])),
            EmitterFixture::property('any', new MixedType(), false, new DefaultValue(["x\ty"])),
        ]);
        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('8.2', Mutability::IMMUTABLE));

        self::assertStringContainsString('public ?string $text = "x\\n)\\n{",', $code);
        self::assertStringContainsString("public ?array \$lines = [\"a\\tb\", 'plain'],", $code);
        self::assertStringContainsString('public mixed $map = ["a\\nb" => 1],', $code);
        self::assertStringContainsString('public mixed $any = ["x\\ty"],', $code);
    }

    public function testEmitsANativeEnumFromPhp81(): void
    {
        self::assertSame(<<<'PHP'
            <?php

            // @generated by msstc4php/dto-generator — DO NOT EDIT

            declare(strict_types=1);

            namespace App\Dto;

            /**
             * A currency.
             */
            enum Currency: string
            {
                /**
                 * Euro.
                 */
                case EUR = 'EUR';

                case IN_PROGRESS = 'in-progress';
            }

            PHP, (new PhpParserEmitter())->emitEnum($this->currency(), EmitterFixture::target('8.1', Mutability::IMMUTABLE)));
    }

    public function testEmitsAClassOfConstantsBeforePhp81(): void
    {
        self::assertSame(<<<'PHP'
            <?php

            // @generated by msstc4php/dto-generator — DO NOT EDIT

            declare(strict_types=1);

            namespace App\Dto;

            /**
             * A currency.
             */
            final class Currency
            {
                /**
                 * Euro.
                 */
                public const EUR = 'EUR';

                public const IN_PROGRESS = 'in-progress';

                private function __construct()
                {
                }
            }

            PHP, (new PhpParserEmitter())->emitEnum($this->currency(), EmitterFixture::target('8.0', Mutability::IMMUTABLE)));
    }

    public function testEmitsEnumPropertiesAndTheirDefaults(): void
    {
        $currency = EnumType::of($this->currency());
        $class = EmitterFixture::model('App\Dto\Price', null, [
            EmitterFixture::property('currency', new NullableType($currency), false, new DefaultValue('in-progress')),
            EmitterFixture::property('accepted', new NullableType(new ListType($currency)), false, new DefaultValue(['EUR'])),
        ]);

        $modern = (new PhpParserEmitter())->emit($class, EmitterFixture::target('8.1', Mutability::IMMUTABLE));
        $legacy = (new PhpParserEmitter())->emit($class, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringContainsString('public readonly ?Currency $currency = Currency::IN_PROGRESS,', $modern);
        self::assertStringContainsString('public readonly ?array $accepted = [Currency::EUR],', $modern);
        self::assertStringContainsString("     * @var ?Currency::*\n     */\n    private ?string \$currency;", $legacy);
        self::assertStringContainsString('?string $currency = Currency::IN_PROGRESS, ?array $accepted = [Currency::EUR]', $legacy);
    }

    private function currency(): EnumModel
    {
        return new EnumModel(
            ClassName::fromFqcn('App\Dto\Currency'),
            EnumBacking::from(EnumBacking::STRING),
            [new EnumCase('EUR', 'EUR', new DocModel('Euro.')), new EnumCase('IN_PROGRESS', 'in-progress')],
            new DocModel('A currency.'),
            new SchemaLocation('/project/api/openapi.yaml', '/components/schemas/Currency'),
        );
    }

    private function emit(string $mutability, string $php, string $accessors = AccessorStyle::AUTO): string
    {
        $class = EmitterFixture::model('App\Dto\Point', 'A point.', [
            EmitterFixture::property('label', new NullableType(ScalarType::string()), false, new DefaultValue(null)),
            EmitterFixture::property('x', ScalarType::int(), true, null, 'Horizontal.'),
        ], $mutability);

        return (new PhpParserEmitter())->emit($class, EmitterFixture::target($php, $mutability, $accessors));
    }
}
