<?php

declare(strict_types=1);

namespace MSSTC4PHP\DtoGenerator\Tests\Unit\Infrastructure\Emitter;

use LogicException;
use MSSTC4PHP\DtoGenerator\Domain\Model\ArgumentValue;
use MSSTC4PHP\DtoGenerator\Domain\Model\AttributeArgument;
use MSSTC4PHP\DtoGenerator\Domain\Model\AttributeModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\ClassKind;
use MSSTC4PHP\DtoGenerator\Domain\Model\ClassModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\ClassName;
use MSSTC4PHP\DtoGenerator\Domain\Model\ClassType;
use MSSTC4PHP\DtoGenerator\Domain\Model\DiscriminatorModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\DiscriminatorValues;
use MSSTC4PHP\DtoGenerator\Domain\Model\DocModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\EnumBacking;
use MSSTC4PHP\DtoGenerator\Domain\Model\EnumCase;
use MSSTC4PHP\DtoGenerator\Domain\Model\EnumModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\EnumType;
use MSSTC4PHP\DtoGenerator\Domain\Model\ImportAlias;
use MSSTC4PHP\DtoGenerator\Domain\Model\ListType;
use MSSTC4PHP\DtoGenerator\Domain\Model\MixedType;
use MSSTC4PHP\DtoGenerator\Domain\Model\NullableType;
use MSSTC4PHP\DtoGenerator\Domain\Model\PropertyModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\ScalarType;
use MSSTC4PHP\DtoGenerator\Domain\Model\UnionType;
use MSSTC4PHP\DtoGenerator\Domain\Schema\SchemaLocation;
use MSSTC4PHP\DtoGenerator\Domain\Shared\DefaultValue;
use MSSTC4PHP\DtoGenerator\Domain\Target\AccessorStyle;
use MSSTC4PHP\DtoGenerator\Domain\Target\DateTimeClass;
use MSSTC4PHP\DtoGenerator\Domain\Target\MetadataMode;
use MSSTC4PHP\DtoGenerator\Domain\Target\Mutability;
use MSSTC4PHP\DtoGenerator\Domain\Target\PhpVersion;
use MSSTC4PHP\DtoGenerator\Domain\Target\TargetProfile;
use MSSTC4PHP\DtoGenerator\Infrastructure\Emitter\AttributeNames;
use MSSTC4PHP\DtoGenerator\Infrastructure\Emitter\AttributeRenderer;
use MSSTC4PHP\DtoGenerator\Infrastructure\Emitter\PhpParserEmitter;
use MSSTC4PHP\DtoGenerator\Infrastructure\Emitter\TypeRenderer;
use MSSTC4PHP\DtoGenerator\Tests\Support\EmitterFixture;
use PhpParser\BuilderFactory;
use PHPUnit\Framework\TestCase;

final class PhpParserEmitterTest extends TestCase
{
    private const HEAD = "<?php\n\n// @generated by msstc4php/dto-generator — DO NOT EDIT\n\ndeclare(strict_types=1);\n\nnamespace App\\Dto;\n\n/**\n * A point.\n */\n";

    public function testEmitsAnImmutableClassForPhp74(): void
    {
        self::assertSame(self::HEAD . <<<'PHP'
            final class Point
            {
                /**
                 * Horizontal.
                 */
                private int $x;

                private ?string $label;

                public function __construct(int $x, ?string $label = null)
                {
                    $this->x = $x;
                    $this->label = $label;
                }

                public function getLabel(): ?string
                {
                    return $this->label;
                }

                public function withLabel(?string $label): self
                {
                    $clone = clone $this;
                    $clone->label = $label;

                    return $clone;
                }

                public function getX(): int
                {
                    return $this->x;
                }

                public function withX(int $x): self
                {
                    $clone = clone $this;
                    $clone->x = $x;

                    return $clone;
                }
            }

            PHP, $this->emit(Mutability::IMMUTABLE, '7.4'));
    }

    public function testEmitsPublicReadonlyPromotedPropertiesForPhp81(): void
    {
        self::assertSame(self::HEAD . <<<'PHP'
            final class Point
            {
                public function __construct(
                    /**
                     * Horizontal.
                     */
                    public readonly int $x,
                    public readonly ?string $label = null,
                ) {
                }

                public function withLabel(?string $label): self
                {
                    return new self($this->x, $label);
                }

                public function withX(int $x): self
                {
                    return new self($x, $this->label);
                }
            }

            PHP, $this->emit(Mutability::IMMUTABLE, '8.1'));
    }

    public function testEmitsAReadonlyClassForPhp82(): void
    {
        $code = $this->emit(Mutability::IMMUTABLE, '8.2');

        self::assertStringContainsString("final readonly class Point\n", $code);
        self::assertStringContainsString("        public int \$x,\n        public ?string \$label = null,\n", $code);
    }

    public function testClonesWithPropertiesOnPhp85(): void
    {
        self::assertStringContainsString("        return clone(\$this, ['x' => \$x]);\n", $this->emit(Mutability::IMMUTABLE, '8.5'));
    }

    public function testEmitsGettersAndSettersForAMutableClass(): void
    {
        $code = $this->emit(Mutability::MUTABLE, '8.5', AccessorStyle::GETTERS);

        self::assertStringContainsString("        private int \$x,\n        private ?string \$label = null,\n", $code);
        self::assertStringContainsString(<<<'PHP'
                public function setLabel(?string $label): self
                {
                    $this->label = $label;

                    return $this;
                }
            PHP, $code);
        self::assertStringNotContainsString('function with', $code);
    }

    public function testEmitsOnlyPublicPropertiesForAMutablePublicClass(): void
    {
        $code = $this->emit(Mutability::MUTABLE, '7.4', AccessorStyle::PUBLIC_PROPERTIES);

        self::assertStringContainsString("    public ?string \$label;\n", $code);
        self::assertStringNotContainsString('function get', $code);
        self::assertStringNotContainsString('function set', $code);
    }

    public function testDocumentsTypesTheTargetCannotDeclare(): void
    {
        $class = EmitterFixture::model('App\Dto\Sample', null, [EmitterFixture::property('code', new UnionType(ScalarType::int(), ScalarType::string()), true)]);
        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringContainsString("    /**\n     * @var int|string\n     */\n    private \$code;\n", $code);
        self::assertStringContainsString("    /**\n     * @param int|string \$code\n     */\n    public function __construct(\$code)\n", $code);
        self::assertStringContainsString("    /**\n     * @return int|string\n     */\n    public function getCode()\n", $code);
    }

    public function testRenamesTheCloneVariableForAPropertyNamedClone(): void
    {
        $class = EmitterFixture::model('App\Dto\Copy', null, [EmitterFixture::property('clone', ScalarType::int(), true)]);
        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringContainsString("        \$copy = clone \$this;\n        \$copy->clone = \$clone;\n\n        return \$copy;\n", $code);
    }

    public function testMarksDeprecatedPropertiesAndTheirAccessors(): void
    {
        $class = EmitterFixture::model('App\Dto\Old', null, [EmitterFixture::property('id', ScalarType::int(), true, null, null, true)]);
        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertSame(3, substr_count($code, "     * @deprecated\n"));
    }

    public function testEmitsAClassWithoutPropertiesWithoutAConstructor(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::model('App\Dto\Nothing', null, []), EmitterFixture::target('8.2', Mutability::IMMUTABLE));

        self::assertStringEndsWith("final readonly class Nothing\n{\n}\n", $code);
    }

    public function testEmitsAGlobalClassWithoutANamespace(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::model('Point', null, []), EmitterFixture::target('8.2', Mutability::IMMUTABLE));

        self::assertStringNotContainsString('namespace', $code);
        self::assertStringStartsWith("<?php\n\n// @generated by msstc4php/dto-generator — DO NOT EDIT\n\ndeclare(strict_types=1);\n\nfinal readonly class Point\n", $code);
    }

    public function testRejectsInheritedPropertiesWithoutAParent(): void
    {
        $this->expectException(LogicException::class);
        $this->expectExceptionMessage('App\Dto\Tag inherits properties but extends no class.');

        (new PhpParserEmitter())->emit(EmitterFixture::tag(), EmitterFixture::target('8.2', Mutability::IMMUTABLE), [EmitterFixture::property('id', ScalarType::int(), true)]);
    }

    public function testEmitsAbstractAndOpenClasses(): void
    {
        $emitter = new PhpParserEmitter();
        $target = EmitterFixture::target('8.0', Mutability::IMMUTABLE);
        $at = new SchemaLocation('/project/api/openapi.yaml', '/components/schemas/Base');
        $immutable = Mutability::from(Mutability::IMMUTABLE);

        self::assertStringContainsString("\nabstract class Base\n", $emitter->emit(new ClassModel(ClassName::fromFqcn('App\Dto\Base'), ClassKind::from(ClassKind::ABSTRACT), null, [], $immutable, DocModel::none(), $at), $target));
        self::assertStringContainsString("\nclass Base\n", $emitter->emit(new ClassModel(ClassName::fromFqcn('App\Dto\Base'), ClassKind::from(ClassKind::OPEN), null, [], $immutable, DocModel::none(), $at), $target));
    }

    public function testPrintsStringDefaultsWithControlCharactersDoubleQuoted(): void
    {
        $class = EmitterFixture::model('App\Dto\Note', null, [
            EmitterFixture::property('text', new NullableType(ScalarType::string()), false, new DefaultValue("x\n)\n{")),
            EmitterFixture::property('lines', new NullableType(new ListType(ScalarType::string())), false, new DefaultValue(["a\tb", 'plain'])),
            EmitterFixture::property('map', new MixedType(), false, new DefaultValue(["a\nb" => 1])),
            EmitterFixture::property('any', new MixedType(), false, new DefaultValue(["x\ty"])),
        ]);
        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('8.2', Mutability::IMMUTABLE));

        self::assertStringContainsString('public ?string $text = "x\\n)\\n{",', $code);
        self::assertStringContainsString("public ?array \$lines = [\"a\\tb\", 'plain'],", $code);
        self::assertStringContainsString('public mixed $map = ["a\\nb" => 1],', $code);
        self::assertStringContainsString('public mixed $any = ["x\\ty"],', $code);
    }

    public function testEmitsANativeEnumFromPhp81(): void
    {
        self::assertSame(<<<'PHP'
            <?php

            // @generated by msstc4php/dto-generator — DO NOT EDIT

            declare(strict_types=1);

            namespace App\Dto;

            /**
             * A currency.
             */
            enum Currency: string
            {
                /**
                 * Euro.
                 */
                case EUR = 'EUR';

                case IN_PROGRESS = 'in-progress';
            }

            PHP, (new PhpParserEmitter())->emitEnum($this->currency(), EmitterFixture::target('8.1', Mutability::IMMUTABLE)));
    }

    public function testEmitsAClassOfConstantsBeforePhp81(): void
    {
        self::assertSame(<<<'PHP'
            <?php

            // @generated by msstc4php/dto-generator — DO NOT EDIT

            declare(strict_types=1);

            namespace App\Dto;

            /**
             * A currency.
             */
            final class Currency
            {
                /**
                 * Euro.
                 */
                public const EUR = 'EUR';

                public const IN_PROGRESS = 'in-progress';

                private function __construct()
                {
                }
            }

            PHP, (new PhpParserEmitter())->emitEnum($this->currency(), EmitterFixture::target('8.0', Mutability::IMMUTABLE)));
    }

    public function testEmitsEnumPropertiesAndTheirDefaults(): void
    {
        $currency = EnumType::of($this->currency());
        $class = EmitterFixture::model('App\Dto\Price', null, [
            EmitterFixture::property('currency', new NullableType($currency), false, new DefaultValue('in-progress')),
            EmitterFixture::property('accepted', new NullableType(new ListType($currency)), false, new DefaultValue(['EUR'])),
        ]);

        $modern = (new PhpParserEmitter())->emit($class, EmitterFixture::target('8.1', Mutability::IMMUTABLE));
        $legacy = (new PhpParserEmitter())->emit($class, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringContainsString('public readonly ?Currency $currency = Currency::IN_PROGRESS,', $modern);
        self::assertStringContainsString('public readonly ?array $accepted = [Currency::EUR],', $modern);
        self::assertStringContainsString("     * @phpstan-var Currency::*|null\n     */\n    private ?string \$currency;", $legacy);
        self::assertStringContainsString("     * @var ?list<string>\n     * @phpstan-var list<Currency::*>|null\n", $legacy);
        self::assertStringContainsString('?string $currency = Currency::IN_PROGRESS, ?array $accepted = [Currency::EUR]', $legacy);
    }

    private function currency(): EnumModel
    {
        return new EnumModel(
            ClassName::fromFqcn('App\Dto\Currency'),
            EnumBacking::from(EnumBacking::STRING),
            [new EnumCase('EUR', 'EUR', new DocModel('Euro.')), new EnumCase('IN_PROGRESS', 'in-progress')],
            new DocModel('A currency.'),
            new SchemaLocation('/project/api/openapi.yaml', '/components/schemas/Currency'),
        );
    }

    private function emit(string $mutability, string $php, string $accessors = AccessorStyle::AUTO): string
    {
        $class = EmitterFixture::model('App\Dto\Point', 'A point.', [
            EmitterFixture::property('label', new NullableType(ScalarType::string()), false, new DefaultValue(null)),
            EmitterFixture::property('x', ScalarType::int(), true, null, 'Horizontal.'),
        ], $mutability);

        return (new PhpParserEmitter())->emit($class, EmitterFixture::target($php, $mutability, $accessors));
    }

    public function testGivesABaseProtectedPropertiesAndCloningWithersReturningStatic(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::animal(Mutability::IMMUTABLE), EmitterFixture::target('8.0', Mutability::IMMUTABLE));

        self::assertStringContainsString("\nclass Animal\n", $code);
        self::assertStringContainsString('public function __construct(protected string $id, protected ?string $nickname = null)', $code);
        self::assertStringContainsString('public function getId(): string', $code);
        self::assertStringContainsString("    public function withId(string \$id): static\n    {\n        \$clone = clone \$this;\n", $code);
    }

    public function testDocumentsTheStaticReturnOfABaseOnPhp74(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::animal(Mutability::IMMUTABLE), EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringContainsString("    /**\n     * @return static\n     */\n    public function withId(string \$id): self\n", $code);
    }

    public function testGivesABaseNoWithersWhereOnlyNewSelfCouldCopyIt(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::animal(Mutability::IMMUTABLE), EmitterFixture::target('8.1', Mutability::IMMUTABLE));

        self::assertStringNotContainsString('function with', $code);
    }

    public function testClonesWithPropertiesInABaseOnPhp85(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::animal(Mutability::IMMUTABLE), EmitterFixture::target('8.5', Mutability::IMMUTABLE));

        self::assertStringContainsString("    public function withId(string \$id): static\n    {\n        return clone(\$this, ['id' => \$id]);\n    }", $code);
    }

    public function testPassesInheritedParametersToTheParentConstructor(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::dog(Mutability::IMMUTABLE), EmitterFixture::target('8.1', Mutability::IMMUTABLE), EmitterFixture::animal(Mutability::IMMUTABLE)->properties());

        self::assertStringContainsString("\nfinal class Dog extends Animal\n", $code);
        self::assertStringContainsString(
            "    public function __construct(\n        string \$id,\n        public readonly string \$breed,\n        ?string \$nickname = null,\n        public readonly ?bool \$goodBoy = true,\n    ) {\n        parent::__construct(\$id, \$nickname);\n    }",
            $code,
        );
        self::assertStringContainsString("    public function withId(string \$id): self\n    {\n        return new self(\$id, \$this->breed, \$this->nickname, \$this->goodBoy);\n    }", $code);
        self::assertStringContainsString('public function withBreed(string $breed): self', $code);
        self::assertSame(1, substr_count($code, 'function withId('));
    }

    public function testAssignsOwnPropertiesAfterTheParentConstructorOnPhp74(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::dog(Mutability::IMMUTABLE), EmitterFixture::target('7.4', Mutability::IMMUTABLE), EmitterFixture::animal(Mutability::IMMUTABLE)->properties());

        self::assertStringContainsString("    private string \$breed;\n", $code);
        self::assertStringNotContainsString('$id;', $code);
        self::assertStringContainsString("        parent::__construct(\$id, \$nickname);\n        \$this->breed = \$breed;\n        \$this->goodBoy = \$goodBoy;\n", $code);
        // The base clones itself for its own withers, so the subclass only adds those of its own properties.
        self::assertStringNotContainsString('withId', $code);
        self::assertStringContainsString("        \$clone = clone \$this;\n        \$clone->breed = \$breed;\n", $code);
    }

    public function testDocumentsInheritedParametersThePromotedSignatureCannotDeclare(): void
    {
        $base = EmitterFixture::model('App\Dto\Base', null, [
            EmitterFixture::property('code', new UnionType(ScalarType::int(), ScalarType::string()), true),
            EmitterFixture::property('name', ScalarType::string('non-empty-string'), true),
        ])
            ->withHierarchy(ClassKind::from(ClassKind::OPEN), null, null)
        ;
        $child = EmitterFixture::model('App\Dto\Child', null, [EmitterFixture::property('label', ScalarType::string('non-empty-string'), true)])
            ->withHierarchy(ClassKind::from(ClassKind::FINAL), $base->name(), null)
        ;
        $code = (new PhpParserEmitter())->emit($child, EmitterFixture::target('7.4', Mutability::IMMUTABLE), $base->properties());

        self::assertStringContainsString("    /**\n     * @param int|string \$code\n     * @phpstan-param non-empty-string \$name\n     * @phpstan-param non-empty-string \$label\n     */\n    public function __construct(", $code);
    }

    public function testProtectsTheConstructorOfAnAbstractBase(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::shape(Mutability::IMMUTABLE), EmitterFixture::target('8.2', Mutability::IMMUTABLE));

        self::assertStringContainsString("\nabstract readonly class Shape\n", $code);
        self::assertStringContainsString('protected function __construct(public string $kind)', $code);
    }

    public function testKeepsSettersOfABaseAndGivesTheChildItsOwn(): void
    {
        $emitter = new PhpParserEmitter();
        $target = EmitterFixture::target('8.2', Mutability::MUTABLE, AccessorStyle::GETTERS);
        $base = $emitter->emit(EmitterFixture::animal(Mutability::MUTABLE), $target);
        $child = $emitter->emit(EmitterFixture::dog(Mutability::MUTABLE), $target, EmitterFixture::animal(Mutability::MUTABLE)->properties());

        self::assertStringContainsString('public function setId(string $id): static', $base);
        self::assertStringContainsString('protected string $id', $base);
        self::assertStringContainsString('public function setBreed(string $breed): self', $child);
        self::assertStringNotContainsString('setId', $child);
        self::assertStringContainsString('private string $breed', $child);
    }

    public function testExtendsAParentFromAnotherNamespace(): void
    {
        $child = EmitterFixture::model('App\Dto\Public\Dog', null, [])->withHierarchy(ClassKind::from(ClassKind::FINAL), ClassName::fromFqcn('App\Dto\Shared\Animal'), null);
        $code = (new PhpParserEmitter())->emit($child, EmitterFixture::target('8.2', Mutability::IMMUTABLE), EmitterFixture::animal(Mutability::IMMUTABLE)->properties());

        self::assertStringContainsString("final readonly class Dog extends \\App\\Dto\\Shared\\Animal\n", $code);
        self::assertStringContainsString('public function __construct(string $id, ?string $nickname = null)', $code);
    }

    public function testRendersAttributesOfTheClassAndItsPromotedProperties(): void
    {
        $class = EmitterFixture::model('App\Dto\Order', null, [
            EmitterFixture::property('id', ScalarType::int(), true)->withAddedAttributes(
                new AttributeModel(ClassName::fromFqcn('App\Attr\Constraints\Positive'), [], new ImportAlias('App\Attr\Constraints', 'Assert')),
                new AttributeModel(ClassName::fromFqcn('App\Dto\Marker')),
            ),
            EmitterFixture::property('note', new NullableType(ScalarType::string()), false, new DefaultValue(null)),
        ])->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Table'), [AttributeArgument::named('name', ArgumentValue::literal('orders'))]));

        $code = (new PhpParserEmitter())->emit($class, $this->attributesTarget('8.2'));

        self::assertStringContainsString("namespace App\\Dto;\n\nuse App\\Attr\\Constraints as Assert;\n\n#[\\App\\Attr\\Table(name: 'orders')]\nfinal readonly class Order\n", $code);
        self::assertStringContainsString('#[Assert\Positive] #[Marker] public int $id', $code);
        self::assertStringContainsString('public ?string $note = null', $code);
        self::assertStringNotContainsString('#[Assert\Positive] #[Marker] public ?string', $code);
    }

    public function testRendersEveryKindOfAttributeArgument(): void
    {
        $tag = ClassName::fromFqcn('App\Dto\Tag');
        $attribute = new AttributeModel(ClassName::fromFqcn('App\Attr\Rule'), [
            AttributeArgument::positional(ArgumentValue::literal("a\nb")),
            AttributeArgument::positional(ArgumentValue::listOf(ArgumentValue::literal(1), ArgumentValue::literal(null))),
            AttributeArgument::named('map', ArgumentValue::mapOf(['k' => ArgumentValue::literal(true), 3 => ArgumentValue::literal(1.5)])),
            AttributeArgument::named('mode', ArgumentValue::constant('STRICT', ClassName::fromFqcn('App\Attr\Level'))),
            AttributeArgument::named('limit', ArgumentValue::constant('PHP_INT_MAX')),
            AttributeArgument::named('target', ArgumentValue::classReference($tag)),
            AttributeArgument::named('inner', ArgumentValue::newInstance(ClassName::fromFqcn('App\Attr\Inner'), AttributeArgument::named('size', ArgumentValue::literal(2)))),
        ]);
        $class = EmitterFixture::model('App\Dto\Order', null, [])->withAddedAttributes($attribute);

        $code = (new PhpParserEmitter())->emit($class, $this->attributesTarget('8.1'));

        self::assertStringContainsString(
            '#[\App\Attr\Rule(
    "a\nb",
    [1, null],
    map: [\'k\' => true, 3 => 1.5],
    mode: \App\Attr\Level::STRICT,
    limit: \PHP_INT_MAX,
    target: Tag::class,
    inner: new \App\Attr\Inner(size: 2),
)]
final class Order
',
            $code,
        );
    }

    public function testLeavesAttributesOutWithoutAttributeMetadata(): void
    {
        $class = EmitterFixture::model('App\Dto\Order', null, [
            EmitterFixture::property('id', ScalarType::int(), true)->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Id'))),
        ])->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Table'), [], new ImportAlias('App\Attr', 'Attr')));

        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('8.2', Mutability::IMMUTABLE, AccessorStyle::AUTO, MetadataMode::NONE));

        self::assertStringNotContainsString('#[', $code);
        self::assertStringNotContainsString('use ', $code);
    }

    public function testRendersAttributesOfASubclassOnItsOwnParametersOnly(): void
    {
        $dog = EmitterFixture::dog(Mutability::IMMUTABLE);
        $dog = $dog->withProperties($dog->properties()[0]->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Breed'))), $dog->properties()[1]);

        $animal = EmitterFixture::animal(Mutability::IMMUTABLE);
        $inherited = [$animal->properties()[0]->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Id'))), $animal->properties()[1]];

        $code = (new PhpParserEmitter())->emit($dog, $this->attributesTarget('8.2'), $inherited);

        self::assertStringContainsString('#[\App\Attr\Breed] public string $breed', $code);
        self::assertStringNotContainsString('App\Attr\Id', $code);
    }

    public function testRendersAttributesInAGlobalFile(): void
    {
        $class = EmitterFixture::model('Point', null, [])->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Table'), [], new ImportAlias('App\Attr', 'Attr')));

        $code = (new PhpParserEmitter())->emit($class, $this->attributesTarget('8.2'));

        self::assertStringContainsString("declare(strict_types=1);\n\nuse App\\Attr as Attr;\n\n#[Attr\\Table]\nfinal readonly class Point\n", $code);
    }

    private function attributesTarget(string $php): TargetProfile
    {
        return new TargetProfile(
            PhpVersion::fromString($php),
            MetadataMode::from(MetadataMode::ATTRIBUTES),
            Mutability::from(Mutability::IMMUTABLE),
            AccessorStyle::from(AccessorStyle::AUTO),
            DateTimeClass::from(DateTimeClass::IMMUTABLE),
            true,
        );
    }

    public function testWritesAnAttributeInFullWhenItsAliasMatchesANameOfTheFile(): void
    {
        $alias = new ImportAlias('Symfony\Component\Validator\Constraints', 'Assert');
        $assert = EmitterFixture::model('App\Dto\Assert', null, [])
            ->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('Symfony\Component\Validator\Constraints\Valid'), [], $alias))
        ;
        $form = EmitterFixture::model('App\Dto\Form', null, [
            EmitterFixture::property('rule', new ClassType(ClassName::fromFqcn('App\Dto\ASSERT')), true)
                ->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('Symfony\Component\Validator\Constraints\Valid'), [], $alias)),
            EmitterFixture::property('other', ScalarType::int(), true)
                ->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Sub\Mark'), [], new ImportAlias('App\Attr\Sub', 'Sub'))),
            EmitterFixture::property('check', new ClassType(ClassName::fromFqcn('App\Dto\Check')), true)
                ->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Checks\Strict'), [], new ImportAlias('App\Checks', 'Check'))),
        ]);

        $assertCode = (new PhpParserEmitter())->emit($assert, $this->attributesTarget('8.2'));
        $formCode = (new PhpParserEmitter())->emit($form, $this->attributesTarget('8.2'));

        self::assertStringNotContainsString('use ', $assertCode);
        self::assertStringContainsString("#[\\Symfony\\Component\\Validator\\Constraints\\Valid]\nfinal readonly class Assert\n", $assertCode);
        self::assertStringContainsString('#[\\Symfony\\Component\\Validator\\Constraints\\Valid] public ASSERT $rule', $formCode);
        self::assertStringContainsString("use App\\Attr\\Sub as Sub;\n", $formCode);
        self::assertStringContainsString('#[Sub\\Mark] public int $other', $formCode);
        self::assertStringContainsString('#[\\App\\Checks\\Strict] public Check $check', $formCode);
        self::assertStringNotContainsString('as Check;', $formCode);
    }

    public function testWritesAnAttributeInFullWhenItsAliasMatchesANameOnlyThePhpDocUses(): void
    {
        $class = EmitterFixture::model('App\\Dto\\Box', null, [
            EmitterFixture::property('items', new ListType(new ClassType(ClassName::fromFqcn('App\\Dto\\Item'))), true)
                ->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\\Rules\\Count'), [], new ImportAlias('App\\Rules', 'Item'))),
        ]);

        $code = (new PhpParserEmitter())->emit($class, $this->attributesTarget('8.2'));

        self::assertStringContainsString('@var list<Item>', $code);
        self::assertStringContainsString('#[\\App\\Rules\\Count] public array $items', $code);
        self::assertStringNotContainsString('use ', $code);
    }

    public function testRefusesAnAliasWhateverTheCaseItIsGivenIn(): void
    {
        $types = new TypeRenderer('App\\Dto', $this->attributesTarget('8.2'));
        $names = new AttributeNames($types, ['Assert']);
        $renderer = new AttributeRenderer($types, new BuilderFactory(), $names, MetadataMode::from(MetadataMode::ATTRIBUTES));

        $renderer->groups([new AttributeModel(ClassName::fromFqcn('Lib\\Constraints\\Valid'), [], new ImportAlias('Lib\\Constraints', 'assert'))]);

        self::assertSame([], $names->uses());
    }

    public function testRendersAnnotationsInTheDocBlocksOfTheClassAndItsProperties(): void
    {
        $class = EmitterFixture::model('App\Dto\Order', 'An order.', [
            EmitterFixture::property('id', ScalarType::int('positive-int'), true)->withAddedAttributes(
                new AttributeModel(ClassName::fromFqcn('App\Attr\Constraints\Positive'), [], new ImportAlias('App\Attr\Constraints', 'Assert')),
                new AttributeModel(ClassName::fromFqcn('App\Dto\Marker')),
            ),
            EmitterFixture::property('note', new NullableType(ScalarType::string()), false, new DefaultValue(null)),
        ])->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Table'), [AttributeArgument::named('name', ArgumentValue::literal('orders'))]));

        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringContainsString("namespace App\\Dto;\n\nuse App\\Attr\\Constraints as Assert;\n\n/**\n * An order.\n *\n * @\\App\\Attr\\Table(name=\"orders\")\n */\nfinal class Order\n", $code);
        self::assertStringContainsString("    /**\n     * @phpstan-var positive-int\n     * @Assert\\Positive\n     * @Marker\n     */\n    private int \$id;\n", $code);
        self::assertStringContainsString("    private ?string \$note;\n", $code);
        self::assertStringNotContainsString('#[', $code);
    }

    public function testRendersEveryKindOfAnnotationArgument(): void
    {
        $attribute = new AttributeModel(ClassName::fromFqcn('App\Attr\Rule'), [
            AttributeArgument::positional(ArgumentValue::listOf(ArgumentValue::literal("say \"hi\"\n*/"), ArgumentValue::literal('C:\\dir'), ArgumentValue::literal(1), ArgumentValue::literal(null), ArgumentValue::literal(2.0))),
            AttributeArgument::named('map', ArgumentValue::mapOf(['k' => ArgumentValue::literal(true), 3 => ArgumentValue::literal(false)])),
            AttributeArgument::named('mode', ArgumentValue::constant('STRICT', ClassName::fromFqcn('App\Attr\Level'))),
            AttributeArgument::named('limit', ArgumentValue::constant('PHP_INT_MAX')),
            AttributeArgument::named('target', ArgumentValue::classReference(ClassName::fromFqcn('App\Dto\Tag'))),
            AttributeArgument::named('status', ArgumentValue::constant('ACTIVE', ClassName::fromFqcn('App\Dto\Status'))),
            AttributeArgument::named('inner', ArgumentValue::listOf(
                ArgumentValue::newInstance(ClassName::fromFqcn('App\Attr\Inner'), AttributeArgument::named('size', ArgumentValue::literal(2))),
                ArgumentValue::newInstance(ClassName::fromFqcn('App\Attr\Blank')),
            )),
        ]);
        $class = EmitterFixture::model('App\Dto\Order', null, [])->withAddedAttributes($attribute);

        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringContainsString(
            "/**\n * @\\App\\Attr\\Rule(\n *     {\"say \"\"hi\"\"\\n*\\/\", \"C:\\dir\", 1, null, 2.0},\n *     map={\"k\"=true, 3=false},\n *     mode=\\App\\Attr\\Level::STRICT,\n *     limit=PHP_INT_MAX,\n *     target=\\App\\Dto\\Tag::class,\n *     status=\\App\\Dto\\Status::ACTIVE,\n *     inner={@\\App\\Attr\\Inner(size=2), @\\App\\Attr\\Blank}\n * )\n */\nfinal class Order\n",
            $code,
        );
    }

    public function testWrapsANestedAnnotationValueThatIsTooLongForItsLine(): void
    {
        $length = static fn (AttributeArgument ...$arguments): ArgumentValue => ArgumentValue::newInstance(ClassName::fromFqcn('App\Attr\Length'), ...$arguments);
        $class = EmitterFixture::model('App\Dto\Order', null, [])->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Rule'), [
            AttributeArgument::named('inner', ArgumentValue::listOf(
                $length(AttributeArgument::named('min', ArgumentValue::literal(1)), AttributeArgument::named('message', ArgumentValue::literal('Far too long for its column.'))),
                $length(AttributeArgument::named('max', ArgumentValue::literal(2))),
            )),
            AttributeArgument::named('strict', ArgumentValue::literal(true)),
        ]));

        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringContainsString(
            "/**\n * @\\App\\Attr\\Rule(\n *     inner={\n *         @\\App\\Attr\\Length(min=1, message=\"Far too long for its column.\"),\n *         @\\App\\Attr\\Length(max=2)\n *     },\n *     strict=true\n * )\n */\n",
            $code,
        );
    }

    public function testKeepsAnAnnotationOfExactlyTheLineLimitOnOneLine(): void
    {
        $text = str_repeat('x', 76);
        $class = EmitterFixture::model('App\Dto\Order', null, [])->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Note'), [AttributeArgument::named('text', ArgumentValue::literal($text))]));

        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringContainsString(' * @\App\Attr\Note(text="' . $text . '")' . "\n", $code);
    }

    public function testPutsTheAnnotationsOfADeprecatedClassAfterItsDeprecation(): void
    {
        $class = new ClassModel(
            ClassName::fromFqcn('App\Dto\Old'),
            ClassKind::from(ClassKind::FINAL),
            null,
            [],
            Mutability::from(Mutability::IMMUTABLE),
            new DocModel('Old.', true),
            new SchemaLocation('/project/api/openapi.yaml', '/components/schemas/Old'),
        );

        $code = (new PhpParserEmitter())->emit($class->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Id'))), EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringContainsString("/**\n * Old.\n *\n * @deprecated\n * @\\App\\Attr\\Id\n */\nfinal class Old\n", $code);
    }

    public function testCollectsSeveralPositionalAnnotationArgumentsIntoValue(): void
    {
        $class = EmitterFixture::model('App\Dto\Order', null, [])->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Pair'), [
            AttributeArgument::positional(ArgumentValue::literal('a')),
            AttributeArgument::positional(ArgumentValue::literal('b')),
            AttributeArgument::named('strict', ArgumentValue::literal(true)),
        ]));

        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringContainsString(' * @\App\Attr\Pair(value={"a", "b"}, strict=true)' . "\n", $code);
    }

    public function testRendersAnnotationsOnPromotedParametersWhenAsked(): void
    {
        $class = EmitterFixture::model('App\Dto\Order', null, [
            EmitterFixture::property('id', ScalarType::int(), true)->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Id'))),
        ]);

        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('8.0', Mutability::IMMUTABLE, AccessorStyle::AUTO, MetadataMode::ANNOTATIONS));

        self::assertStringContainsString("        /**\n         * @\\App\\Attr\\Id\n         */\n        private int \$id", $code);
        self::assertStringNotContainsString('#[', $code);
    }

    public function testWritesAnAnnotationInFullWhenItsAliasMatchesANameOfTheFile(): void
    {
        $class = EmitterFixture::model('App\Dto\Assert', null, [])
            ->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('Lib\Constraints\Valid'), [], new ImportAlias('Lib\Constraints', 'Assert')))
        ;

        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringNotContainsString('use ', $code);
        self::assertStringContainsString(' * @\Lib\Constraints\Valid' . "\n", $code);
    }

    public function testChecksTheDiscriminatorBeforeCallingTheParent(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::circle(), EmitterFixture::target('8.2', Mutability::IMMUTABLE), EmitterFixture::shape()->properties());

        self::assertStringContainsString(
            "    public function __construct(string \$kind, public float \$radius)\n    {\n"
            . "        if (\$kind !== 'circle' && \$kind !== 'round') {\n"
            . "            throw new \\InvalidArgumentException(sprintf('\"%s\" does not select Circle by \"kind\".', \$kind));\n"
            . "        }\n\n"
            . "        parent::__construct(\$kind);\n    }",
            $code,
        );
        self::assertStringContainsString('return new self($this->kind, $radius);', $code);
        self::assertStringNotContainsString('withKind', $code);
    }

    public function testMovesADefaultedDiscriminatorBehindTheRequiredParameters(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::square(), EmitterFixture::target('8.1', Mutability::IMMUTABLE), EmitterFixture::shape()->properties());

        self::assertStringContainsString("    public function __construct(public readonly float \$side, string \$kind = 'square')\n", $code);
        self::assertStringContainsString("        if (\$kind !== 'square') {\n", $code);
        self::assertStringContainsString("        parent::__construct(\$kind);\n", $code);
        self::assertStringContainsString("    public function withSide(float \$side): self\n    {\n        return new self(\$side, \$this->kind);\n    }", $code);
        self::assertStringNotContainsString('withKind', $code);
    }

    public function testComparesAnEnumDiscriminatorWithItsCases(): void
    {
        $inherited = EmitterFixture::wallet()->properties();
        $modern = (new PhpParserEmitter())->emit(EmitterFixture::euroWallet(), EmitterFixture::target('8.1', Mutability::IMMUTABLE), $inherited);
        $legacy = (new PhpParserEmitter())->emit(EmitterFixture::euroWallet(), EmitterFixture::target('7.4', Mutability::IMMUTABLE), $inherited);

        self::assertStringContainsString('public function __construct(public readonly int $balance, Currency $currency = Currency::EUR)', $modern);
        self::assertStringContainsString('if ($currency !== Currency::EUR) {', $modern);
        self::assertStringContainsString("does not select EuroWallet by \"currency\".', \$currency->value)", $modern);
        self::assertStringContainsString('public function __construct(int $balance, string $currency = Currency::EUR)', $legacy);
        self::assertStringContainsString('if ($currency !== Currency::EUR) {', $legacy);
        self::assertStringContainsString("does not select EuroWallet by \"currency\".', \$currency)", $legacy);
    }

    public function testReadsTheValueOfANullableEnumSafely(): void
    {
        $currency = EnumType::of(EmitterFixture::currency());
        $purse = EmitterFixture::model('App\Dto\Purse', null, [EmitterFixture::property('currency', new NullableType($currency), false, new DefaultValue(null))])
            ->withHierarchy(ClassKind::from(ClassKind::ABSTRACT), null, new DiscriminatorModel('currency', ['EUR' => ClassName::fromFqcn('App\Dto\Coin')]))
        ;
        $coin = EmitterFixture::model('App\Dto\Coin', null, [])
            ->withHierarchy(ClassKind::from(ClassKind::FINAL), $purse->name(), null)
            ->withDiscriminatorValues(new DiscriminatorValues('currency', ['EUR', 'in-progress']))
        ;

        $code = (new PhpParserEmitter())->emit($coin, EmitterFixture::target('8.1', Mutability::IMMUTABLE), $purse->properties());

        self::assertStringContainsString('public function __construct(?Currency $currency)', $code);
        self::assertStringContainsString('if ($currency !== Currency::EUR && $currency !== Currency::IN_PROGRESS) {', $code);
        self::assertStringContainsString('$currency?->value', $code);
    }

    public function testEscapesTheWireNameInTheMessageFormat(): void
    {
        $wire = "pet%type's";
        $petType = new PropertyModel('petType', $wire, ScalarType::string(), true, null, DocModel::none(), new SchemaLocation('/project/api/openapi.yaml', '/components/schemas/Pet'));
        $pet = EmitterFixture::model('App\Dto\Pet', null, [$petType])
            ->withHierarchy(ClassKind::from(ClassKind::ABSTRACT), null, new DiscriminatorModel($wire, ['cat' => ClassName::fromFqcn('App\Dto\Cat')]))
        ;
        $cat = EmitterFixture::model('App\Dto\Cat', null, [])
            ->withHierarchy(ClassKind::from(ClassKind::FINAL), $pet->name(), null)
            ->withDiscriminatorValues(new DiscriminatorValues('petType', ['cat']))
        ;

        $code = (new PhpParserEmitter())->emit($cat, EmitterFixture::target('8.2', Mutability::IMMUTABLE), $pet->properties());

        self::assertStringContainsString("sprintf('\"%s\" does not select Cat by \"pet%%type\\'s\".', \$petType)", $code);
    }

    public function testLeavesOutACheckTheTypeAlreadyMakes(): void
    {
        $square = EmitterFixture::model('App\Dto\Square', null, [])
            ->withHierarchy(ClassKind::from(ClassKind::FINAL), ClassName::fromFqcn('App\Dto\Shape'), null)
            ->withDiscriminatorValues(new DiscriminatorValues('kind', ['square'], false))
        ;

        $code = (new PhpParserEmitter())->emit($square, EmitterFixture::target('8.2', Mutability::IMMUTABLE), EmitterFixture::shape()->properties());

        self::assertStringContainsString("    public function __construct(string \$kind = 'square')\n    {\n        parent::__construct(\$kind);\n    }", $code);
        self::assertStringNotContainsString('InvalidArgumentException', $code);
    }

    public function testKeepsAPropertyDefaultOnlyWhenItSelectsTheClass(): void
    {
        $choice = EmitterFixture::model('App\Dto\Choice', null, [
            EmitterFixture::property('mode', new NullableType(ScalarType::string()), false, new DefaultValue('a')),
            EmitterFixture::property('size', new NullableType(ScalarType::int()), false, new DefaultValue(null)),
        ])->withHierarchy(ClassKind::from(ClassKind::ABSTRACT), null, new DiscriminatorModel('mode', ['a' => ClassName::fromFqcn('App\Dto\Pick')]));
        $pick = static fn (string ...$values): ClassModel => EmitterFixture::model('App\Dto\Pick', null, [EmitterFixture::property('label', ScalarType::string(), true)])
            ->withHierarchy(ClassKind::from(ClassKind::FINAL), $choice->name(), null)
            ->withDiscriminatorValues(new DiscriminatorValues('mode', $values))
        ;
        $target = EmitterFixture::target('8.2', Mutability::IMMUTABLE);

        $kept = (new PhpParserEmitter())->emit($pick('a', 'b'), $target, $choice->properties());
        $dropped = (new PhpParserEmitter())->emit($pick('b', 'c'), $target, $choice->properties());

        self::assertStringContainsString("public function __construct(public string \$label, ?string \$mode = 'a', ?int \$size = null)", $kept);
        self::assertStringContainsString('public function __construct(public string $label, ?string $mode, ?int $size = null)', $dropped);
        self::assertStringContainsString('parent::__construct($mode, $size);', $dropped);
    }

    public function testGivesTheDiscriminatorNoSetterOrWither(): void
    {
        $emitter = new PhpParserEmitter();
        foreach (['7.4', '8.0', '8.5'] as $php) {
            self::assertStringNotContainsString('withKind', $emitter->emit(EmitterFixture::shape(), EmitterFixture::target($php, Mutability::IMMUTABLE)), $php);
        }

        $mutable = $emitter->emit(EmitterFixture::shape(Mutability::MUTABLE), EmitterFixture::target('8.2', Mutability::MUTABLE, AccessorStyle::GETTERS));
        self::assertStringNotContainsString('setKind', $mutable);
        self::assertStringContainsString('public function getKind(): string', $mutable);

        // The only variant of a base keeps the discriminator as its own property.
        $solo = EmitterFixture::model('App\Dto\Solo', null, [EmitterFixture::property('kind', ScalarType::string(), true)])
            ->withDiscriminatorValues(new DiscriminatorValues('kind', ['solo']))
        ;
        $code = $emitter->emit($solo, EmitterFixture::target('8.5', Mutability::IMMUTABLE));
        self::assertStringContainsString("public function __construct(public string \$kind = 'solo')", $code);
        self::assertStringNotContainsString('withKind', $code);
    }

    public function testRejectsDiscriminatorValuesOfAnUndeclaredProperty(): void
    {
        $this->expectException(LogicException::class);
        $this->expectExceptionMessage('App\Dto\Tag checks the discriminator $kind, which it neither declares nor inherits.');

        (new PhpParserEmitter())->emit(EmitterFixture::tag()->withDiscriminatorValues(new DiscriminatorValues('kind', ['tag'])), EmitterFixture::target('8.2', Mutability::IMMUTABLE));
    }

    public function testLeavesWithersOutWhenTheTargetHasNone(): void
    {
        $emitter = new PhpParserEmitter();

        self::assertStringNotContainsString('function with', $emitter->emit(EmitterFixture::sample(), EmitterFixture::target('8.2', Mutability::IMMUTABLE, AccessorStyle::AUTO, null, false)));
        self::assertStringNotContainsString('function with', $emitter->emit(EmitterFixture::animal(), EmitterFixture::target('7.4', Mutability::IMMUTABLE, AccessorStyle::AUTO, null, false)));
        self::assertStringNotContainsString(
            'function with',
            $emitter->emit(EmitterFixture::dog(), EmitterFixture::target('8.1', Mutability::IMMUTABLE, AccessorStyle::AUTO, null, false), EmitterFixture::animal()->properties()),
        );
        self::assertStringContainsString(
            'public function setId(int $id): self',
            $emitter->emit(EmitterFixture::sample(Mutability::MUTABLE), EmitterFixture::target('8.2', Mutability::MUTABLE, AccessorStyle::GETTERS, null, false)),
        );
    }

    public function testChecksEveryDiscriminatorRootFirst(): void
    {
        $inherited = [EmitterFixture::property('kind', ScalarType::string(), true), EmitterFixture::property('breed', ScalarType::string(), true)];
        $siamese = EmitterFixture::model('App\Dto\Siamese', null, [])
            ->withHierarchy(ClassKind::from(ClassKind::FINAL), ClassName::fromFqcn('App\Dto\Cat'), null)
            ->withDiscriminatorValues(new DiscriminatorValues('kind', ['cat', 'kitty']), new DiscriminatorValues('breed', ['siamese']))
        ;

        $code = (new PhpParserEmitter())->emit($siamese, EmitterFixture::target('8.2', Mutability::IMMUTABLE), $inherited);

        self::assertStringContainsString(
            "    public function __construct(string \$kind, string \$breed = 'siamese')\n    {\n"
            . "        if (\$kind !== 'cat' && \$kind !== 'kitty') {\n"
            . "            throw new \\InvalidArgumentException(sprintf('\"%s\" does not select Siamese by \"kind\".', \$kind));\n"
            . "        }\n\n"
            . "        if (\$breed !== 'siamese') {\n"
            . "            throw new \\InvalidArgumentException(sprintf('\"%s\" does not select Siamese by \"breed\".', \$breed));\n"
            . "        }\n\n"
            . "        parent::__construct(\$kind, \$breed);\n    }",
            $code,
        );
    }

    public function testGivesNoMutatorToAPropertyAnyDiscriminatorOfTheLineageReads(): void
    {
        $emitter = new PhpParserEmitter();
        $top = EmitterFixture::top()->properties();
        foreach (['7.4', '8.0', '8.5'] as $php) {
            $mid = $emitter->emit(EmitterFixture::mid(), EmitterFixture::target($php, Mutability::IMMUTABLE), $top);
            self::assertStringNotContainsString('withKind', $mid, $php);
            self::assertStringNotContainsString('withSub', $mid, $php);
        }

        $mutable = $emitter->emit(EmitterFixture::mid(Mutability::MUTABLE), EmitterFixture::target('8.2', Mutability::MUTABLE, AccessorStyle::GETTERS), $top);
        self::assertStringNotContainsString('setKind', $mutable);
        self::assertStringContainsString('public function getKind(): string', $mutable);

        // A variant without checked values still rebuilds itself for the inherited properties, but not for `kind`.
        $blobX = $emitter->emit(EmitterFixture::blobX(), EmitterFixture::target('8.1', Mutability::IMMUTABLE), EmitterFixture::blob()->properties());
        self::assertStringNotContainsString('withKind', $blobX);
        self::assertStringContainsString('public function withSize(int $size): self', $blobX);
    }

    public function testDeclaresACheckedOptionalDiscriminatorWithoutNull(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::side(), EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        // The check rejects null before the assignment; PHPStan reports a nullable type that never holds it.
        self::assertStringContainsString('    private string $kind;', $code);
        self::assertStringContainsString('public function getKind(): string', $code);
        self::assertStringContainsString("public function __construct(string \$c, ?string \$kind = 's')", $code);

        $promoted = (new PhpParserEmitter())->emit(EmitterFixture::side(), EmitterFixture::target('8.0', Mutability::IMMUTABLE));
        self::assertStringContainsString('public function getKind(): ?string', $promoted);
    }

    public function testDocumentsADeclaredCheckedEnumDiscriminatorWithoutNull(): void
    {
        $coin = EmitterFixture::model('App\Dto\Coin', null, [
            EmitterFixture::property('currency', new NullableType(EnumType::of(EmitterFixture::currency())), false, new DefaultValue(null)),
        ])
            ->withHierarchy(ClassKind::from(ClassKind::FINAL), null, null)
            ->withDiscriminatorValues(new DiscriminatorValues('currency', ['EUR']))
        ;

        $code = (new PhpParserEmitter())->emit($coin, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringContainsString("    /**\n     * @phpstan-var Currency::*\n     */\n    private string \$currency;", $code);
    }
}
