<?php

declare(strict_types=1);

namespace MSSTC4PHP\DtoGenerator\Tests\Unit\Infrastructure\Emitter;

use LogicException;
use MSSTC4PHP\DtoGenerator\Domain\Model\ArgumentValue;
use MSSTC4PHP\DtoGenerator\Domain\Model\AttributeArgument;
use MSSTC4PHP\DtoGenerator\Domain\Model\AttributeModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\ClassKind;
use MSSTC4PHP\DtoGenerator\Domain\Model\ClassModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\ClassName;
use MSSTC4PHP\DtoGenerator\Domain\Model\ClassType;
use MSSTC4PHP\DtoGenerator\Domain\Model\DocModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\EnumBacking;
use MSSTC4PHP\DtoGenerator\Domain\Model\EnumCase;
use MSSTC4PHP\DtoGenerator\Domain\Model\EnumModel;
use MSSTC4PHP\DtoGenerator\Domain\Model\EnumType;
use MSSTC4PHP\DtoGenerator\Domain\Model\ImportAlias;
use MSSTC4PHP\DtoGenerator\Domain\Model\ListType;
use MSSTC4PHP\DtoGenerator\Domain\Model\MixedType;
use MSSTC4PHP\DtoGenerator\Domain\Model\NullableType;
use MSSTC4PHP\DtoGenerator\Domain\Model\ScalarType;
use MSSTC4PHP\DtoGenerator\Domain\Model\UnionType;
use MSSTC4PHP\DtoGenerator\Domain\Schema\SchemaLocation;
use MSSTC4PHP\DtoGenerator\Domain\Shared\DefaultValue;
use MSSTC4PHP\DtoGenerator\Domain\Target\AccessorStyle;
use MSSTC4PHP\DtoGenerator\Domain\Target\DateTimeClass;
use MSSTC4PHP\DtoGenerator\Domain\Target\MetadataMode;
use MSSTC4PHP\DtoGenerator\Domain\Target\Mutability;
use MSSTC4PHP\DtoGenerator\Domain\Target\PhpVersion;
use MSSTC4PHP\DtoGenerator\Domain\Target\TargetProfile;
use MSSTC4PHP\DtoGenerator\Infrastructure\Emitter\PhpParserEmitter;
use MSSTC4PHP\DtoGenerator\Tests\Support\EmitterFixture;
use PHPUnit\Framework\TestCase;

final class PhpParserEmitterTest extends TestCase
{
    private const HEAD = "<?php\n\n// @generated by msstc4php/dto-generator — DO NOT EDIT\n\ndeclare(strict_types=1);\n\nnamespace App\\Dto;\n\n/**\n * A point.\n */\n";

    public function testEmitsAnImmutableClassForPhp74(): void
    {
        self::assertSame(self::HEAD . <<<'PHP'
            final class Point
            {
                /**
                 * Horizontal.
                 */
                private int $x;

                private ?string $label;

                public function __construct(int $x, ?string $label = null)
                {
                    $this->x = $x;
                    $this->label = $label;
                }

                public function getLabel(): ?string
                {
                    return $this->label;
                }

                public function withLabel(?string $label): self
                {
                    $clone = clone $this;
                    $clone->label = $label;

                    return $clone;
                }

                public function getX(): int
                {
                    return $this->x;
                }

                public function withX(int $x): self
                {
                    $clone = clone $this;
                    $clone->x = $x;

                    return $clone;
                }
            }

            PHP, $this->emit(Mutability::IMMUTABLE, '7.4'));
    }

    public function testEmitsPublicReadonlyPromotedPropertiesForPhp81(): void
    {
        self::assertSame(self::HEAD . <<<'PHP'
            final class Point
            {
                public function __construct(
                    /**
                     * Horizontal.
                     */
                    public readonly int $x,
                    public readonly ?string $label = null,
                ) {
                }

                public function withLabel(?string $label): self
                {
                    return new self($this->x, $label);
                }

                public function withX(int $x): self
                {
                    return new self($x, $this->label);
                }
            }

            PHP, $this->emit(Mutability::IMMUTABLE, '8.1'));
    }

    public function testEmitsAReadonlyClassForPhp82(): void
    {
        $code = $this->emit(Mutability::IMMUTABLE, '8.2');

        self::assertStringContainsString("final readonly class Point\n", $code);
        self::assertStringContainsString("        public int \$x,\n        public ?string \$label = null,\n", $code);
    }

    public function testClonesWithPropertiesOnPhp85(): void
    {
        self::assertStringContainsString("        return clone(\$this, ['x' => \$x]);\n", $this->emit(Mutability::IMMUTABLE, '8.5'));
    }

    public function testEmitsGettersAndSettersForAMutableClass(): void
    {
        $code = $this->emit(Mutability::MUTABLE, '8.5', AccessorStyle::GETTERS);

        self::assertStringContainsString("        private int \$x,\n        private ?string \$label = null,\n", $code);
        self::assertStringContainsString(<<<'PHP'
                public function setLabel(?string $label): self
                {
                    $this->label = $label;

                    return $this;
                }
            PHP, $code);
        self::assertStringNotContainsString('function with', $code);
    }

    public function testEmitsOnlyPublicPropertiesForAMutablePublicClass(): void
    {
        $code = $this->emit(Mutability::MUTABLE, '7.4', AccessorStyle::PUBLIC_PROPERTIES);

        self::assertStringContainsString("    public ?string \$label;\n", $code);
        self::assertStringNotContainsString('function get', $code);
        self::assertStringNotContainsString('function set', $code);
    }

    public function testDocumentsTypesTheTargetCannotDeclare(): void
    {
        $class = EmitterFixture::model('App\Dto\Sample', null, [EmitterFixture::sample()->properties()[3]]);
        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringContainsString("    /**\n     * @var int|string\n     */\n    private \$code;\n", $code);
        self::assertStringContainsString("    /**\n     * @param int|string \$code\n     */\n    public function __construct(\$code)\n", $code);
        self::assertStringContainsString("    /**\n     * @return int|string\n     */\n    public function getCode()\n", $code);
    }

    public function testRenamesTheCloneVariableForAPropertyNamedClone(): void
    {
        $class = EmitterFixture::model('App\Dto\Copy', null, [EmitterFixture::property('clone', ScalarType::int(), true)]);
        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringContainsString("        \$copy = clone \$this;\n        \$copy->clone = \$clone;\n\n        return \$copy;\n", $code);
    }

    public function testMarksDeprecatedPropertiesAndTheirAccessors(): void
    {
        $class = EmitterFixture::model('App\Dto\Old', null, [EmitterFixture::property('id', ScalarType::int(), true, null, null, true)]);
        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertSame(3, substr_count($code, "     * @deprecated\n"));
    }

    public function testEmitsAClassWithoutPropertiesWithoutAConstructor(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::model('App\Dto\Nothing', null, []), EmitterFixture::target('8.2', Mutability::IMMUTABLE));

        self::assertStringEndsWith("final readonly class Nothing\n{\n}\n", $code);
    }

    public function testEmitsAGlobalClassWithoutANamespace(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::model('Point', null, []), EmitterFixture::target('8.2', Mutability::IMMUTABLE));

        self::assertStringNotContainsString('namespace', $code);
        self::assertStringStartsWith("<?php\n\n// @generated by msstc4php/dto-generator — DO NOT EDIT\n\ndeclare(strict_types=1);\n\nfinal readonly class Point\n", $code);
    }

    public function testRejectsInheritedPropertiesWithoutAParent(): void
    {
        $this->expectException(LogicException::class);
        $this->expectExceptionMessage('App\Dto\Tag inherits properties but extends no class.');

        (new PhpParserEmitter())->emit(EmitterFixture::tag(), EmitterFixture::target('8.2', Mutability::IMMUTABLE), [EmitterFixture::property('id', ScalarType::int(), true)]);
    }

    public function testEmitsAbstractAndOpenClasses(): void
    {
        $emitter = new PhpParserEmitter();
        $target = EmitterFixture::target('8.0', Mutability::IMMUTABLE);
        $at = new SchemaLocation('/project/api/openapi.yaml', '/components/schemas/Base');
        $immutable = Mutability::from(Mutability::IMMUTABLE);

        self::assertStringContainsString("\nabstract class Base\n", $emitter->emit(new ClassModel(ClassName::fromFqcn('App\Dto\Base'), ClassKind::from(ClassKind::ABSTRACT), null, [], $immutable, DocModel::none(), $at), $target));
        self::assertStringContainsString("\nclass Base\n", $emitter->emit(new ClassModel(ClassName::fromFqcn('App\Dto\Base'), ClassKind::from(ClassKind::OPEN), null, [], $immutable, DocModel::none(), $at), $target));
    }

    public function testPrintsStringDefaultsWithControlCharactersDoubleQuoted(): void
    {
        $class = EmitterFixture::model('App\Dto\Note', null, [
            EmitterFixture::property('text', new NullableType(ScalarType::string()), false, new DefaultValue("x\n)\n{")),
            EmitterFixture::property('lines', new NullableType(new ListType(ScalarType::string())), false, new DefaultValue(["a\tb", 'plain'])),
            EmitterFixture::property('map', new MixedType(), false, new DefaultValue(["a\nb" => 1])),
            EmitterFixture::property('any', new MixedType(), false, new DefaultValue(["x\ty"])),
        ]);
        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('8.2', Mutability::IMMUTABLE));

        self::assertStringContainsString('public ?string $text = "x\\n)\\n{",', $code);
        self::assertStringContainsString("public ?array \$lines = [\"a\\tb\", 'plain'],", $code);
        self::assertStringContainsString('public mixed $map = ["a\\nb" => 1],', $code);
        self::assertStringContainsString('public mixed $any = ["x\\ty"],', $code);
    }

    public function testEmitsANativeEnumFromPhp81(): void
    {
        self::assertSame(<<<'PHP'
            <?php

            // @generated by msstc4php/dto-generator — DO NOT EDIT

            declare(strict_types=1);

            namespace App\Dto;

            /**
             * A currency.
             */
            enum Currency: string
            {
                /**
                 * Euro.
                 */
                case EUR = 'EUR';

                case IN_PROGRESS = 'in-progress';
            }

            PHP, (new PhpParserEmitter())->emitEnum($this->currency(), EmitterFixture::target('8.1', Mutability::IMMUTABLE)));
    }

    public function testEmitsAClassOfConstantsBeforePhp81(): void
    {
        self::assertSame(<<<'PHP'
            <?php

            // @generated by msstc4php/dto-generator — DO NOT EDIT

            declare(strict_types=1);

            namespace App\Dto;

            /**
             * A currency.
             */
            final class Currency
            {
                /**
                 * Euro.
                 */
                public const EUR = 'EUR';

                public const IN_PROGRESS = 'in-progress';

                private function __construct()
                {
                }
            }

            PHP, (new PhpParserEmitter())->emitEnum($this->currency(), EmitterFixture::target('8.0', Mutability::IMMUTABLE)));
    }

    public function testEmitsEnumPropertiesAndTheirDefaults(): void
    {
        $currency = EnumType::of($this->currency());
        $class = EmitterFixture::model('App\Dto\Price', null, [
            EmitterFixture::property('currency', new NullableType($currency), false, new DefaultValue('in-progress')),
            EmitterFixture::property('accepted', new NullableType(new ListType($currency)), false, new DefaultValue(['EUR'])),
        ]);

        $modern = (new PhpParserEmitter())->emit($class, EmitterFixture::target('8.1', Mutability::IMMUTABLE));
        $legacy = (new PhpParserEmitter())->emit($class, EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringContainsString('public readonly ?Currency $currency = Currency::IN_PROGRESS,', $modern);
        self::assertStringContainsString('public readonly ?array $accepted = [Currency::EUR],', $modern);
        self::assertStringContainsString("     * @var ?Currency::*\n     */\n    private ?string \$currency;", $legacy);
        self::assertStringContainsString('?string $currency = Currency::IN_PROGRESS, ?array $accepted = [Currency::EUR]', $legacy);
    }

    private function currency(): EnumModel
    {
        return new EnumModel(
            ClassName::fromFqcn('App\Dto\Currency'),
            EnumBacking::from(EnumBacking::STRING),
            [new EnumCase('EUR', 'EUR', new DocModel('Euro.')), new EnumCase('IN_PROGRESS', 'in-progress')],
            new DocModel('A currency.'),
            new SchemaLocation('/project/api/openapi.yaml', '/components/schemas/Currency'),
        );
    }

    private function emit(string $mutability, string $php, string $accessors = AccessorStyle::AUTO): string
    {
        $class = EmitterFixture::model('App\Dto\Point', 'A point.', [
            EmitterFixture::property('label', new NullableType(ScalarType::string()), false, new DefaultValue(null)),
            EmitterFixture::property('x', ScalarType::int(), true, null, 'Horizontal.'),
        ], $mutability);

        return (new PhpParserEmitter())->emit($class, EmitterFixture::target($php, $mutability, $accessors));
    }

    public function testGivesABaseProtectedPropertiesAndCloningWithersReturningStatic(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::animal(Mutability::IMMUTABLE), EmitterFixture::target('8.0', Mutability::IMMUTABLE));

        self::assertStringContainsString("\nclass Animal\n", $code);
        self::assertStringContainsString('public function __construct(protected string $id, protected ?string $nickname = null)', $code);
        self::assertStringContainsString('public function getId(): string', $code);
        self::assertStringContainsString("    public function withId(string \$id): static\n    {\n        \$clone = clone \$this;\n", $code);
    }

    public function testDocumentsTheStaticReturnOfABaseOnPhp74(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::animal(Mutability::IMMUTABLE), EmitterFixture::target('7.4', Mutability::IMMUTABLE));

        self::assertStringContainsString("    /**\n     * @return static\n     */\n    public function withId(string \$id): self\n", $code);
    }

    public function testGivesABaseNoWithersWhereOnlyNewSelfCouldCopyIt(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::animal(Mutability::IMMUTABLE), EmitterFixture::target('8.1', Mutability::IMMUTABLE));

        self::assertStringNotContainsString('function with', $code);
    }

    public function testClonesWithPropertiesInABaseOnPhp85(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::animal(Mutability::IMMUTABLE), EmitterFixture::target('8.5', Mutability::IMMUTABLE));

        self::assertStringContainsString("    public function withId(string \$id): static\n    {\n        return clone(\$this, ['id' => \$id]);\n    }", $code);
    }

    public function testPassesInheritedParametersToTheParentConstructor(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::dog(Mutability::IMMUTABLE), EmitterFixture::target('8.1', Mutability::IMMUTABLE), EmitterFixture::animal(Mutability::IMMUTABLE)->properties());

        self::assertStringContainsString("\nfinal class Dog extends Animal\n", $code);
        self::assertStringContainsString(
            "    public function __construct(\n        string \$id,\n        public readonly string \$breed,\n        ?string \$nickname = null,\n        public readonly ?bool \$goodBoy = true,\n    ) {\n        parent::__construct(\$id, \$nickname);\n    }",
            $code,
        );
        self::assertStringContainsString("    public function withId(string \$id): self\n    {\n        return new self(\$id, \$this->breed, \$this->nickname, \$this->goodBoy);\n    }", $code);
        self::assertStringContainsString('public function withBreed(string $breed): self', $code);
        self::assertSame(1, substr_count($code, 'function withId('));
    }

    public function testAssignsOwnPropertiesAfterTheParentConstructorOnPhp74(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::dog(Mutability::IMMUTABLE), EmitterFixture::target('7.4', Mutability::IMMUTABLE), EmitterFixture::animal(Mutability::IMMUTABLE)->properties());

        self::assertStringContainsString("    private string \$breed;\n", $code);
        self::assertStringNotContainsString('$id;', $code);
        self::assertStringContainsString("        parent::__construct(\$id, \$nickname);\n        \$this->breed = \$breed;\n        \$this->goodBoy = \$goodBoy;\n", $code);
        // The base clones itself for its own withers, so the subclass only adds those of its own properties.
        self::assertStringNotContainsString('withId', $code);
        self::assertStringContainsString("        \$clone = clone \$this;\n        \$clone->breed = \$breed;\n", $code);
    }

    public function testDocumentsInheritedParametersThePromotedSignatureCannotDeclare(): void
    {
        $base = EmitterFixture::model('App\Dto\Base', null, [
            EmitterFixture::property('code', new UnionType(ScalarType::int(), ScalarType::string()), true),
            EmitterFixture::property('name', ScalarType::string('non-empty-string'), true),
        ])
            ->withHierarchy(ClassKind::from(ClassKind::OPEN), null, null)
        ;
        $child = EmitterFixture::model('App\Dto\Child', null, [EmitterFixture::property('label', ScalarType::string('non-empty-string'), true)])
            ->withHierarchy(ClassKind::from(ClassKind::FINAL), $base->name(), null)
        ;
        $code = (new PhpParserEmitter())->emit($child, EmitterFixture::target('7.4', Mutability::IMMUTABLE), $base->properties());

        self::assertStringContainsString("    /**\n     * @param int|string \$code\n     * @param non-empty-string \$name\n     * @param non-empty-string \$label\n     */\n    public function __construct(", $code);
    }

    public function testProtectsTheConstructorOfAnAbstractBase(): void
    {
        $code = (new PhpParserEmitter())->emit(EmitterFixture::shape(Mutability::IMMUTABLE), EmitterFixture::target('8.2', Mutability::IMMUTABLE));

        self::assertStringContainsString("\nabstract readonly class Shape\n", $code);
        self::assertStringContainsString('protected function __construct(public string $kind)', $code);
    }

    public function testKeepsSettersOfABaseAndGivesTheChildItsOwn(): void
    {
        $emitter = new PhpParserEmitter();
        $target = EmitterFixture::target('8.2', Mutability::MUTABLE, AccessorStyle::GETTERS);
        $base = $emitter->emit(EmitterFixture::animal(Mutability::MUTABLE), $target);
        $child = $emitter->emit(EmitterFixture::dog(Mutability::MUTABLE), $target, EmitterFixture::animal(Mutability::MUTABLE)->properties());

        self::assertStringContainsString('public function setId(string $id): static', $base);
        self::assertStringContainsString('protected string $id', $base);
        self::assertStringContainsString('public function setBreed(string $breed): self', $child);
        self::assertStringNotContainsString('setId', $child);
        self::assertStringContainsString('private string $breed', $child);
    }

    public function testExtendsAParentFromAnotherNamespace(): void
    {
        $child = EmitterFixture::model('App\Dto\Public\Dog', null, [])->withHierarchy(ClassKind::from(ClassKind::FINAL), ClassName::fromFqcn('App\Dto\Shared\Animal'), null);
        $code = (new PhpParserEmitter())->emit($child, EmitterFixture::target('8.2', Mutability::IMMUTABLE), EmitterFixture::animal(Mutability::IMMUTABLE)->properties());

        self::assertStringContainsString("final readonly class Dog extends \\App\\Dto\\Shared\\Animal\n", $code);
        self::assertStringContainsString('public function __construct(string $id, ?string $nickname = null)', $code);
    }

    public function testRendersAttributesOfTheClassAndItsPromotedProperties(): void
    {
        $class = EmitterFixture::model('App\Dto\Order', null, [
            EmitterFixture::property('id', ScalarType::int(), true)->withAddedAttributes(
                new AttributeModel(ClassName::fromFqcn('App\Attr\Constraints\Positive'), [], new ImportAlias('App\Attr\Constraints', 'Assert')),
                new AttributeModel(ClassName::fromFqcn('App\Dto\Marker')),
            ),
            EmitterFixture::property('note', new NullableType(ScalarType::string()), false, new DefaultValue(null)),
        ])->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Table'), [AttributeArgument::named('name', ArgumentValue::literal('orders'))]));

        $code = (new PhpParserEmitter())->emit($class, $this->attributesTarget('8.2'));

        self::assertStringContainsString("namespace App\\Dto;\n\nuse App\\Attr\\Constraints as Assert;\n\n#[\\App\\Attr\\Table(name: 'orders')]\nfinal readonly class Order\n", $code);
        self::assertStringContainsString('#[Assert\Positive] #[Marker] public int $id', $code);
        self::assertStringContainsString('public ?string $note = null', $code);
        self::assertStringNotContainsString('#[Assert\Positive] #[Marker] public ?string', $code);
    }

    public function testRendersEveryKindOfAttributeArgument(): void
    {
        $tag = ClassName::fromFqcn('App\Dto\Tag');
        $attribute = new AttributeModel(ClassName::fromFqcn('App\Attr\Rule'), [
            AttributeArgument::positional(ArgumentValue::literal("a\nb")),
            AttributeArgument::positional(ArgumentValue::listOf(ArgumentValue::literal(1), ArgumentValue::literal(null))),
            AttributeArgument::named('map', ArgumentValue::mapOf(['k' => ArgumentValue::literal(true), 3 => ArgumentValue::literal(1.5)])),
            AttributeArgument::named('mode', ArgumentValue::constant('STRICT', ClassName::fromFqcn('App\Attr\Level'))),
            AttributeArgument::named('limit', ArgumentValue::constant('PHP_INT_MAX')),
            AttributeArgument::named('target', ArgumentValue::classReference($tag)),
            AttributeArgument::named('inner', ArgumentValue::newInstance(ClassName::fromFqcn('App\Attr\Inner'), AttributeArgument::named('size', ArgumentValue::literal(2)))),
        ]);
        $class = EmitterFixture::model('App\Dto\Order', null, [])->withAddedAttributes($attribute);

        $code = (new PhpParserEmitter())->emit($class, $this->attributesTarget('8.1'));

        self::assertStringContainsString(
            '#[\App\Attr\Rule(
    "a\nb",
    [1, null],
    map: [\'k\' => true, 3 => 1.5],
    mode: \App\Attr\Level::STRICT,
    limit: \PHP_INT_MAX,
    target: Tag::class,
    inner: new \App\Attr\Inner(size: 2),
)]
final class Order
',
            $code,
        );
    }

    public function testLeavesAttributesOutWithoutAttributeMetadata(): void
    {
        $class = EmitterFixture::model('App\Dto\Order', null, [
            EmitterFixture::property('id', ScalarType::int(), true)->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Id'))),
        ])->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Table'), [], new ImportAlias('App\Attr', 'Attr')));

        $code = (new PhpParserEmitter())->emit($class, EmitterFixture::target('8.2', Mutability::IMMUTABLE, AccessorStyle::AUTO, MetadataMode::NONE));

        self::assertStringNotContainsString('#[', $code);
        self::assertStringNotContainsString('use ', $code);
    }

    public function testRendersAttributesOfASubclassOnItsOwnParametersOnly(): void
    {
        $dog = EmitterFixture::dog(Mutability::IMMUTABLE);
        $dog = $dog->withProperties($dog->properties()[0]->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Breed'))), $dog->properties()[1]);

        $animal = EmitterFixture::animal(Mutability::IMMUTABLE);
        $inherited = [$animal->properties()[0]->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Id'))), $animal->properties()[1]];

        $code = (new PhpParserEmitter())->emit($dog, $this->attributesTarget('8.2'), $inherited);

        self::assertStringContainsString('#[\App\Attr\Breed] public string $breed', $code);
        self::assertStringNotContainsString('App\Attr\Id', $code);
    }

    public function testRendersAttributesInAGlobalFile(): void
    {
        $class = EmitterFixture::model('Point', null, [])->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Table'), [], new ImportAlias('App\Attr', 'Attr')));

        $code = (new PhpParserEmitter())->emit($class, $this->attributesTarget('8.2'));

        self::assertStringContainsString("declare(strict_types=1);\n\nuse App\\Attr as Attr;\n\n#[Attr\\Table]\nfinal readonly class Point\n", $code);
    }

    private function attributesTarget(string $php): TargetProfile
    {
        return new TargetProfile(
            PhpVersion::fromString($php),
            MetadataMode::from(MetadataMode::ATTRIBUTES),
            Mutability::from(Mutability::IMMUTABLE),
            AccessorStyle::from(AccessorStyle::AUTO),
            DateTimeClass::from(DateTimeClass::IMMUTABLE),
            true,
        );
    }

    public function testWritesAnAttributeInFullWhenItsAliasMatchesANameOfTheFile(): void
    {
        $alias = new ImportAlias('Symfony\Component\Validator\Constraints', 'Assert');
        $assert = EmitterFixture::model('App\Dto\Assert', null, [])
            ->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('Symfony\Component\Validator\Constraints\Valid'), [], $alias))
        ;
        $form = EmitterFixture::model('App\Dto\Form', null, [
            EmitterFixture::property('rule', new ClassType(ClassName::fromFqcn('App\Dto\ASSERT')), true)
                ->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('Symfony\Component\Validator\Constraints\Valid'), [], $alias)),
            EmitterFixture::property('other', ScalarType::int(), true)
                ->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Attr\Sub\Mark'), [], new ImportAlias('App\Attr\Sub', 'Sub'))),
            EmitterFixture::property('check', new ClassType(ClassName::fromFqcn('App\Dto\Check')), true)
                ->withAddedAttributes(new AttributeModel(ClassName::fromFqcn('App\Checks\Strict'), [], new ImportAlias('App\Checks', 'Check'))),
        ]);

        $assertCode = (new PhpParserEmitter())->emit($assert, $this->attributesTarget('8.2'));
        $formCode = (new PhpParserEmitter())->emit($form, $this->attributesTarget('8.2'));

        self::assertStringNotContainsString('use ', $assertCode);
        self::assertStringContainsString("#[\\Symfony\\Component\\Validator\\Constraints\\Valid]\nfinal readonly class Assert\n", $assertCode);
        self::assertStringContainsString('#[\\Symfony\\Component\\Validator\\Constraints\\Valid] public ASSERT $rule', $formCode);
        self::assertStringContainsString("use App\\Attr\\Sub as Sub;\n", $formCode);
        self::assertStringContainsString('#[Sub\\Mark] public int $other', $formCode);
        self::assertStringContainsString('#[\\App\\Checks\\Strict] public Check $check', $formCode);
        self::assertStringNotContainsString('as Check;', $formCode);
    }
}
