<?php

declare(strict_types=1);

namespace MSSTC4PHP\DtoGenerator\Tests\Integration\Infrastructure\Writer;

use MSSTC4PHP\DtoGenerator\Application\Port\WriteFailed;
use MSSTC4PHP\DtoGenerator\Application\Service\Generate\FileChange;
use MSSTC4PHP\DtoGenerator\Application\Service\Generate\GeneratedFile;
use MSSTC4PHP\DtoGenerator\Application\Service\Generate\WritePlan;
use MSSTC4PHP\DtoGenerator\Infrastructure\Writer\FilesystemWriter;
use PHPUnit\Framework\TestCase;

final class FilesystemWriterTest extends TestCase
{
    private const HEADER = "<?php\n\n// @generated by msstc4php/dto-generator — DO NOT EDIT\n\n";

    private string $dir;

    protected function setUp(): void
    {
        $this->dir = sys_get_temp_dir() . '/dto-generator-writer-' . bin2hex(random_bytes(6));
        mkdir($this->dir);
    }

    protected function tearDown(): void
    {
        self::remove($this->dir);
    }

    public function testCreatesFilesAndAManifest(): void
    {
        $plan = $this->write([$this->file('User.php', 'user'), $this->file('Sub/Tag.php', 'tag')]);

        self::assertSame([['create', 'Sub/Tag.php'], ['create', 'User.php']], $this->summary($plan));
        self::assertSame(self::HEADER . 'user', file_get_contents($this->dir . '/out/User.php'));
        self::assertSame(self::HEADER . 'tag', file_get_contents($this->dir . '/out/Sub/Tag.php'));
        self::assertSame(
            "{\n    \"generator\": \"msstc4php/dto-generator\",\n    \"files\": {\n"
            . '        "Sub/Tag.php": "' . hash('sha256', self::HEADER . 'tag') . "\",\n"
            . '        "User.php": "' . hash('sha256', self::HEADER . 'user') . "\"\n    }\n}\n",
            file_get_contents($this->dir . '/out/.dto-generator.manifest.json'),
        );
        self::assertSame('0644', substr(sprintf('%o', fileperms($this->dir . '/out/User.php')), -4));
        self::assertSame([], glob($this->dir . '/out/.*.tmp'));
    }

    public function testLeavesAnUnchangedOutputAlone(): void
    {
        $files = [$this->file('User.php', 'user')];
        $this->write($files);
        touch($this->dir . '/out/User.php', 1000000000);
        touch($this->dir . '/out/.dto-generator.manifest.json', 1000000000);
        clearstatcache();

        $plan = $this->write($files);

        self::assertFalse($plan->hasChanges());
        self::assertSame([['unchanged', 'User.php']], $this->summary($plan));
        clearstatcache();
        self::assertSame(1000000000, filemtime($this->dir . '/out/User.php'));
        self::assertSame(1000000000, filemtime($this->dir . '/out/.dto-generator.manifest.json'));
    }

    public function testUpdatesAChangedFile(): void
    {
        $this->write([$this->file('User.php', 'old')]);

        $plan = $this->write([$this->file('User.php', 'new')]);

        self::assertSame([['update', 'User.php']], $this->summary($plan));
        self::assertSame(self::HEADER . 'new', file_get_contents($this->dir . '/out/User.php'));
    }

    public function testDeletesStaleFiles(): void
    {
        $this->write([$this->file('User.php', 'user'), $this->file('Old.php', 'old')]);

        $plan = $this->write([$this->file('User.php', 'user')]);

        self::assertSame([['unchanged', 'User.php'], ['delete', 'Old.php']], $this->summary($plan));
        self::assertFileDoesNotExist($this->dir . '/out/Old.php');
        self::assertStringNotContainsString('Old.php', (string) file_get_contents($this->dir . '/out/.dto-generator.manifest.json'));
    }

    public function testForgetsStaleFilesThatAreAlreadyGone(): void
    {
        $this->write([$this->file('User.php', 'user'), $this->file('Old.php', 'old')]);
        unlink($this->dir . '/out/Old.php');

        $plan = $this->write([$this->file('User.php', 'user')]);

        self::assertSame([['unchanged', 'User.php']], $this->summary($plan));
        self::assertStringNotContainsString('Old.php', (string) file_get_contents($this->dir . '/out/.dto-generator.manifest.json'));
    }

    public function testRefusesToOverwriteAFileItDidNotGenerate(): void
    {
        mkdir($this->dir . '/out');
        file_put_contents($this->dir . '/out/User.php', "<?php\n// hand-written\n");

        $plan = (new FilesystemWriter())->plan([$this->dir . '/out'], [$this->file('User.php', 'user')]);

        self::assertSame(
            [$this->dir . '/out/User.php' => 'The file exists but was not generated by dto-generator (no "@generated" header); remove it or choose another outputDir.'],
            $plan->conflicts(),
        );
        self::assertSame([], $this->summary($plan));
    }

    public function testKeepsAStaleFileWhoseHeaderWasRemoved(): void
    {
        $this->write([$this->file('User.php', 'user'), $this->file('Old.php', 'old')]);
        file_put_contents($this->dir . '/out/Old.php', "<?php\n// now hand-written\n");

        $plan = (new FilesystemWriter())->plan([$this->dir . '/out'], [$this->file('User.php', 'user')]);

        self::assertSame([$this->dir . '/out/Old.php'], array_keys($plan->conflicts()));
        self::assertSame([['unchanged', 'User.php']], $this->summary($plan));
    }

    public function testSharesOneManifestBetweenSourcesWithTheSameOutputDir(): void
    {
        $this->write([$this->file('User.php', 'user'), new GeneratedFile($this->dir . '/out/', 'Pet.php', self::HEADER . 'pet')]);

        $manifest = (string) file_get_contents($this->dir . '/out/.dto-generator.manifest.json');
        self::assertStringContainsString('"Pet.php"', $manifest);
        self::assertStringContainsString('"User.php"', $manifest);
    }

    public function testTreatsAnUnreadableManifestAsEmpty(): void
    {
        mkdir($this->dir . '/out');
        file_put_contents($this->dir . '/out/.dto-generator.manifest.json', '{broken');

        $plan = $this->write([$this->file('User.php', 'user')]);

        self::assertSame([['create', 'User.php']], $this->summary($plan));
        self::assertStringContainsString('"User.php"', (string) file_get_contents($this->dir . '/out/.dto-generator.manifest.json'));
    }

    public function testIgnoresManifestEntriesThatAreNotStrings(): void
    {
        mkdir($this->dir . '/out');
        file_put_contents($this->dir . '/out/.dto-generator.manifest.json', '{"files": {"A.php": 5, "B.php": "x"}}');
        file_put_contents($this->dir . '/out/B.php', self::HEADER . 'b');

        $plan = $this->write([]);

        self::assertSame([['delete', 'B.php']], $this->summary($plan));
    }

    public function testDoesNothingForAnEmptyPlan(): void
    {
        (new FilesystemWriter())->apply(new WritePlan([], [], []));

        self::assertSame(['.', '..'], scandir($this->dir));
    }

    public function testReportsADirectoryItCannotWrite(): void
    {
        if (function_exists('posix_geteuid') && posix_geteuid() === 0) {
            self::markTestSkipped('root can write anywhere');
        }

        mkdir($this->dir . '/out', 0555);
        $writer = new FilesystemWriter();
        $plan = $writer->plan([$this->dir . '/out'], [$this->file('User.php', 'user')]);

        $this->expectException(WriteFailed::class);
        $this->expectExceptionMessage('Cannot write "' . $this->dir . '/out/User.php"');

        try {
            $writer->apply($plan);
        } finally {
            chmod($this->dir . '/out', 0755);
        }
    }

    public function testReportsAFileItCannotDelete(): void
    {
        if (function_exists('posix_geteuid') && posix_geteuid() === 0) {
            self::markTestSkipped('root can delete anywhere');
        }

        $this->write([$this->file('Old.php', 'old')]);
        chmod($this->dir . '/out', 0555);
        $writer = new FilesystemWriter();
        $plan = $writer->plan([$this->dir . '/out'], []);

        $this->expectException(WriteFailed::class);
        $this->expectExceptionMessage('Cannot delete "' . $this->dir . '/out/Old.php"');

        try {
            $writer->apply($plan);
        } finally {
            chmod($this->dir . '/out', 0755);
        }
    }

    public function testCleansAnOutputDirThatNoLongerGetsFiles(): void
    {
        $this->write([$this->file('User.php', 'user')]);

        $plan = $this->write([]);

        self::assertSame([['delete', 'User.php']], $this->summary($plan));
        self::assertFileDoesNotExist($this->dir . '/out/User.php');
    }

    public function testDoesNotCreateAManifestForAnEmptyNewOutputDir(): void
    {
        $plan = (new FilesystemWriter())->plan([$this->dir . '/fresh'], []);

        self::assertFalse($plan->hasChanges());
    }

    /**
     * @param list<GeneratedFile> $files
     */
    private function write(array $files): WritePlan
    {
        $writer = new FilesystemWriter();
        $plan = $writer->plan([$this->dir . '/out'], $files);
        $writer->apply($plan);

        return $plan;
    }

    private function file(string $relativePath, string $body): GeneratedFile
    {
        return new GeneratedFile($this->dir . '/out', $relativePath, self::HEADER . $body);
    }

    /**
     * @return list<array{string, string}>
     */
    private function summary(WritePlan $plan): array
    {
        return array_map(
            fn (FileChange $change): array => [$change->kind(), substr($change->path(), strlen($this->dir . '/out/'))],
            $plan->changes(),
        );
    }

    private static function remove(string $path): void
    {
        if (is_dir($path) && !is_link($path)) {
            chmod($path, 0755);
            foreach ((array) scandir($path) as $entry) {
                if ($entry !== '.' && $entry !== '..') {
                    self::remove($path . '/' . $entry);
                }
            }

            rmdir($path);
        } elseif (file_exists($path)) {
            unlink($path);
        }
    }
}
