<?php

declare(strict_types=1);

namespace MSSTC4PHP\DtoGenerator\Tests\Integration\Infrastructure\Writer;

use Closure;
use MSSTC4PHP\DtoGenerator\Application\Port\WriteFailed;
use MSSTC4PHP\DtoGenerator\Application\Service\Generate\FileChange;
use MSSTC4PHP\DtoGenerator\Application\Service\Generate\GeneratedFile;
use MSSTC4PHP\DtoGenerator\Application\Service\Generate\WritePlan;
use MSSTC4PHP\DtoGenerator\Infrastructure\Writer\DirectoryLocks;
use MSSTC4PHP\DtoGenerator\Infrastructure\Writer\FilesystemWriter;
use PHPUnit\Framework\TestCase;

final class FilesystemWriterTest extends TestCase
{
    private const HEADER = "<?php\n\n// @generated by msstc4php/dto-generator — DO NOT EDIT\n\n";

    private string $dir;

    protected function setUp(): void
    {
        $this->dir = sys_get_temp_dir() . '/dto-generator-writer-' . bin2hex(random_bytes(6));
        mkdir($this->dir);
    }

    protected function tearDown(): void
    {
        self::remove($this->dir);
    }

    public function testCreatesFilesAndAManifest(): void
    {
        $plan = $this->write([$this->file('User.php', 'user'), $this->file('Sub/Tag.php', 'tag')]);

        self::assertSame([['create', 'Sub/Tag.php'], ['create', 'User.php']], $this->summary($plan));
        self::assertSame(self::HEADER . 'user', file_get_contents($this->dir . '/out/User.php'));
        self::assertSame(self::HEADER . 'tag', file_get_contents($this->dir . '/out/Sub/Tag.php'));
        self::assertSame(
            "{\n    \"generator\": \"msstc4php/dto-generator\",\n    \"files\": {\n"
            . '        "Sub/Tag.php": "' . hash('sha256', self::HEADER . 'tag') . "\",\n"
            . '        "User.php": "' . hash('sha256', self::HEADER . 'user') . "\"\n    }\n}\n",
            file_get_contents($this->dir . '/out/.dto-generator.manifest.json'),
        );
        self::assertSame(sprintf('%o', 0666 & ~umask()), substr(sprintf('%o', fileperms($this->dir . '/out/User.php')), -3));
        self::assertSame(sprintf('%o', 0777 & ~umask()), substr(sprintf('%o', fileperms($this->dir . '/out/Sub')), -3));
        self::assertSame([], glob($this->dir . '/out/.*.tmp'));
    }

    public function testLeavesAnUnchangedOutputAlone(): void
    {
        $files = [$this->file('User.php', 'user')];
        $this->write($files);
        touch($this->dir . '/out/User.php', 1000000000);
        touch($this->dir . '/out/.dto-generator.manifest.json', 1000000000);
        clearstatcache();

        $plan = $this->write($files);

        self::assertFalse($plan->hasChanges());
        self::assertSame([['unchanged', 'User.php']], $this->summary($plan));
        clearstatcache();
        self::assertSame(1000000000, filemtime($this->dir . '/out/User.php'));
        self::assertSame(1000000000, filemtime($this->dir . '/out/.dto-generator.manifest.json'));
    }

    public function testUpdatesAChangedFile(): void
    {
        $this->write([$this->file('User.php', 'old')]);

        $plan = $this->write([$this->file('User.php', 'new')]);

        self::assertSame([['update', 'User.php']], $this->summary($plan));
        self::assertSame(self::HEADER . 'new', file_get_contents($this->dir . '/out/User.php'));
    }

    public function testDeletesStaleFiles(): void
    {
        $this->write([$this->file('User.php', 'user'), $this->file('Old.php', 'old')]);

        $plan = $this->write([$this->file('User.php', 'user')]);

        self::assertSame([['unchanged', 'User.php'], ['delete', 'Old.php']], $this->summary($plan));
        self::assertFileDoesNotExist($this->dir . '/out/Old.php');
        self::assertStringNotContainsString('Old.php', (string) file_get_contents($this->dir . '/out/.dto-generator.manifest.json'));
    }

    public function testForgetsStaleFilesThatAreAlreadyGone(): void
    {
        $this->write([$this->file('User.php', 'user'), $this->file('Old.php', 'old')]);
        unlink($this->dir . '/out/Old.php');

        $plan = $this->write([$this->file('User.php', 'user')]);

        self::assertSame([['unchanged', 'User.php']], $this->summary($plan));
        self::assertStringNotContainsString('Old.php', (string) file_get_contents($this->dir . '/out/.dto-generator.manifest.json'));
    }

    public function testRefusesToOverwriteAFileItDidNotGenerate(): void
    {
        mkdir($this->dir . '/out');
        file_put_contents($this->dir . '/out/User.php', "<?php\n// hand-written\n");

        $plan = (new FilesystemWriter())->plan([$this->dir . '/out'], [$this->file('User.php', 'user')]);

        self::assertSame(
            [$this->dir . '/out/User.php' => 'The file exists but was not generated by dto-generator (no "@generated" header); remove it or choose another outputDir.'],
            $plan->conflicts(),
        );
        self::assertSame([], $this->summary($plan));
    }

    public function testKeepsAStaleFileWhoseHeaderWasRemoved(): void
    {
        $this->write([$this->file('User.php', 'user'), $this->file('Old.php', 'old')]);
        file_put_contents($this->dir . '/out/Old.php', "<?php\n// now hand-written\n");

        $plan = (new FilesystemWriter())->plan([$this->dir . '/out'], [$this->file('User.php', 'user')]);

        self::assertSame([$this->dir . '/out/Old.php'], array_keys($plan->conflicts()));
        self::assertSame([['unchanged', 'User.php']], $this->summary($plan));
    }

    public function testSharesOneManifestBetweenSourcesWithTheSameOutputDir(): void
    {
        $this->write([$this->file('User.php', 'user'), new GeneratedFile($this->dir . '/out/', 'Pet.php', self::HEADER . 'pet')]);

        $manifest = (string) file_get_contents($this->dir . '/out/.dto-generator.manifest.json');
        self::assertStringContainsString('"Pet.php"', $manifest);
        self::assertStringContainsString('"User.php"', $manifest);
    }

    public function testDoesNothingForAnEmptyPlan(): void
    {
        (new FilesystemWriter())->apply(new WritePlan([], [], []));

        self::assertSame(['.', '..'], scandir($this->dir));
    }

    public function testReportsADirectoryItCannotWrite(): void
    {
        if (function_exists('posix_geteuid') && posix_geteuid() === 0) {
            self::markTestSkipped('root can write anywhere');
        }

        mkdir($this->dir . '/out', 0555);
        $writer = new FilesystemWriter();
        $plan = $writer->plan([$this->dir . '/out'], [$this->file('User.php', 'user')]);

        $this->expectException(WriteFailed::class);
        $this->expectExceptionMessage('Cannot write "' . $this->dir . '/out/.dto-generator.manifest.json"');

        try {
            $writer->apply($plan);
        } finally {
            chmod($this->dir . '/out', 0755);
        }
    }

    public function testReportsAFileItCannotDelete(): void
    {
        if (function_exists('posix_geteuid') && posix_geteuid() === 0) {
            self::markTestSkipped('root can delete anywhere');
        }

        $this->write([$this->file('Sub/Old.php', 'old')]);
        chmod($this->dir . '/out/Sub', 0555);
        $writer = new FilesystemWriter();
        $plan = $writer->plan([$this->dir . '/out'], []);

        $this->expectException(WriteFailed::class);
        $this->expectExceptionMessage('Cannot delete "' . $this->dir . '/out/Sub/Old.php"');

        try {
            $writer->apply($plan);
        } finally {
            chmod($this->dir . '/out/Sub', 0755);
        }
    }

    public function testKeepsAStaleFileItCannotRead(): void
    {
        if (function_exists('posix_geteuid') && posix_geteuid() === 0) {
            self::markTestSkipped('root can read anything');
        }

        $this->write([$this->file('Old.php', 'old')]);
        chmod($this->dir . '/out/Old.php', 0000);

        $plan = (new FilesystemWriter())->plan([$this->dir . '/out'], []);

        self::assertSame([$this->dir . '/out/Old.php' => 'The file cannot be read, so it is not deleted.'], $plan->conflicts());
        chmod($this->dir . '/out/Old.php', 0644);
    }

    public function testCleansAnOutputDirThatNoLongerGetsFiles(): void
    {
        $this->write([$this->file('User.php', 'user')]);

        $plan = $this->write([]);

        self::assertSame([['delete', 'User.php']], $this->summary($plan));
        self::assertFileDoesNotExist($this->dir . '/out/User.php');
    }

    public function testDoesNotCreateAManifestForAnEmptyNewOutputDir(): void
    {
        $plan = (new FilesystemWriter())->plan([$this->dir . '/fresh'], []);

        self::assertFalse($plan->hasChanges());
    }

    public function testDeletesEveryStaleFileAfterAKeptOne(): void
    {
        $this->write([$this->file('A.php', 'a'), $this->file('B.php', 'b'), $this->file('C.php', 'c')]);

        $plan = $this->write([$this->file('A.php', 'a')]);

        self::assertSame([['unchanged', 'A.php'], ['delete', 'B.php'], ['delete', 'C.php']], $this->summary($plan));
    }

    public function testAcceptsAnOutputDirWithATrailingSlash(): void
    {
        $this->write([$this->file('User.php', 'user')]);
        $writer = new FilesystemWriter();

        $plan = $writer->plan([$this->dir . '/out/'], []);

        self::assertSame([['delete', 'User.php']], $this->summary($plan));
    }

    public function testKeepsPlanningOtherOutputDirsAfterAnEmptyNewOne(): void
    {
        $plan = (new FilesystemWriter())->plan([$this->dir . '/fresh', $this->dir . '/out'], [$this->file('User.php', 'user')]);

        self::assertSame([$this->dir . '/out/.dto-generator.manifest.json'], array_keys($plan->manifests()));
    }

    public function testKeepsTheManifestSortedWhenAKeptFileSortsFirst(): void
    {
        $this->write([$this->file('A.php', 'a'), $this->file('B.php', 'b')]);
        file_put_contents($this->dir . '/out/A.php', "<?php\n// hand-written now\n");
        $writer = new FilesystemWriter();

        $writer->apply($writer->plan([$this->dir . '/out'], [$this->file('B.php', 'b2')]));

        $manifest = (string) file_get_contents($this->dir . '/out/.dto-generator.manifest.json');
        self::assertLessThan(strpos($manifest, '"B.php"'), strpos($manifest, '"A.php"'));
    }

    public function testRestoresTheErrorHandler(): void
    {
        $this->write([$this->file('User.php', 'user')]);

        $previous = set_error_handler(static fn (): bool => false);
        restore_error_handler();

        // The writer silences warnings with a closure; PHPUnit's own handler is an object.
        self::assertNotInstanceOf(Closure::class, $previous);
    }

    /**
     * @dataProvider corruptManifests
     */
    public function testRefusesToWorkFromACorruptManifest(string $manifest): void
    {
        mkdir($this->dir . '/out');
        file_put_contents($this->dir . '/out/.dto-generator.manifest.json', $manifest);

        $plan = (new FilesystemWriter())->plan([$this->dir . '/out'], [$this->file('User.php', 'user')]);

        self::assertSame(
            [$this->dir . '/out/.dto-generator.manifest.json' => 'The manifest is not a valid dto-generator manifest, so stale files cannot be found; fix it or delete it.'],
            $plan->conflicts(),
        );
    }

    /**
     * @return array<string, array{string}>
     */
    public static function corruptManifests(): array
    {
        return [
            'merge conflict' => ["{\n<<<<<<< HEAD\n}"],
            'no files' => ['{"generator": "msstc4php/dto-generator"}'],
            'files not a map' => ['{"files": "A.php"}'],
            'hash not a string' => ['{"files": {"A.php": 5}}'],
            'path outside the directory' => ['{"files": {"../Victim.php": "x"}}'],
            'absolute path' => ['{"files": {"/etc/Victim.php": "x"}}'],
            'backslash' => ['{"files": {"..\\\\Victim.php": "x"}}'],
        ];
    }

    public function testNeverTouchesAFileOutsideTheOutputDirListedInAManifest(): void
    {
        mkdir($this->dir . '/out');
        file_put_contents($this->dir . '/Victim.php', self::HEADER . 'victim');
        file_put_contents($this->dir . '/out/.dto-generator.manifest.json', '{"files": {"../Victim.php": "x"}}');

        $plan = $this->write([]);

        self::assertSame([], $this->summary($plan));
        self::assertFileExists($this->dir . '/Victim.php');
    }

    public function testRefusesTwoClassesInOneFile(): void
    {
        $plan = (new FilesystemWriter())->plan([$this->dir . '/out'], [
            $this->file('User.php', 'a'),
            $this->file('Tag.php', 'tag'),
            new GeneratedFile($this->dir . '/out/', 'user.php', self::HEADER . 'b'),
        ]);

        self::assertSame(
            [$this->dir . '/out/user.php' => 'Another generated class already maps to this file (letter case ignored); give the sources different outputDirs or the classes different names.'],
            $plan->conflicts(),
        );
    }

    public function testRemovesTheTemporaryFileWhenAWriteFails(): void
    {
        $writer = new FilesystemWriter();
        $plan = $writer->plan([$this->dir . '/out'], [$this->file('User.php', 'user')]);
        // Appears between plan and apply, so the rename over it fails.
        mkdir($this->dir . '/out/User.php', 0777, true);

        try {
            $writer->apply($plan);
            self::fail('The write over a directory succeeded.');
        } catch (WriteFailed $exception) {
            self::assertSame($this->dir . '/out/User.php', $exception->path());
        }

        self::assertSame([], glob($this->dir . '/out/.*.tmp'));
    }

    public function testRecordsEveryFileItMayWriteBeforeWritingAny(): void
    {
        $writer = new FilesystemWriter();
        $plan = $writer->plan([$this->dir . '/out'], [$this->file('A.php', 'a'), $this->file('B.php', 'b')]);
        mkdir($this->dir . '/out/B.php', 0777, true);

        try {
            $writer->apply($plan);
        } catch (WriteFailed $exception) {
        }

        $manifest = (string) file_get_contents($this->dir . '/out/.dto-generator.manifest.json');
        self::assertStringContainsString('"A.php"', $manifest);
        self::assertStringContainsString('"B.php"', $manifest);
    }

    public function testKeepsStaleFilesInTheInterimManifest(): void
    {
        $this->write([$this->file('Old.php', 'old')]);

        $plan = (new FilesystemWriter())->plan([$this->dir . '/out'], [$this->file('New.php', 'new')]);

        $interim = $plan->interimManifests()[$this->dir . '/out/.dto-generator.manifest.json'];
        self::assertStringContainsString('"New.php"', $interim);
        self::assertStringContainsString('"Old.php"', $interim);
        self::assertStringNotContainsString('"Old.php"', $plan->manifests()[$this->dir . '/out/.dto-generator.manifest.json']);
    }

    public function testNeedsNoInterimManifestWhenNothingIsDeleted(): void
    {
        $plan = (new FilesystemWriter())->plan([$this->dir . '/out'], [$this->file('New.php', 'new')]);

        self::assertSame([], $plan->interimManifests());
    }

    public function testRefusesAnOutputDirWithANulByte(): void
    {
        $plan = (new FilesystemWriter())->plan([$this->dir . "/o\0ut"], [new GeneratedFile($this->dir . "/o\0ut", 'User.php', self::HEADER)]);

        self::assertSame([$this->dir . "/o\0ut" => 'The output directory path contains a NUL byte.'], $plan->conflicts());
        self::assertSame([], $plan->changes());
    }

    public function testReportsAFileItCannotRead(): void
    {
        if (function_exists('posix_geteuid') && posix_geteuid() === 0) {
            self::markTestSkipped('root can read anything');
        }

        mkdir($this->dir . '/out');
        file_put_contents($this->dir . '/out/User.php', self::HEADER . 'user');
        chmod($this->dir . '/out/User.php', 0000);

        $plan = (new FilesystemWriter())->plan([$this->dir . '/out'], [$this->file('User.php', 'new')]);

        self::assertSame([$this->dir . '/out/User.php' => 'The file cannot be read, so it is not overwritten.'], $plan->conflicts());
    }

    public function testTreatsWindowsLineEndingsAsUnchanged(): void
    {
        $this->write([$this->file('User.php', "user\nline")]);
        file_put_contents($this->dir . '/out/User.php', str_replace("\n", "\r\n", self::HEADER . "user\nline"));

        $plan = $this->write([$this->file('User.php', "user\nline")]);

        self::assertFalse($plan->hasChanges());
    }

    public function testKeepsThePermissionsOfAnUpdatedFile(): void
    {
        $this->write([$this->file('User.php', 'old')]);
        chmod($this->dir . '/out/User.php', 0664);

        $this->write([$this->file('User.php', 'new')]);

        clearstatcache();
        self::assertSame('0664', substr(sprintf('%o', fileperms($this->dir . '/out/User.php')), -4));
    }

    public function testLocksTheOutputDirFromPlanUntilApply(): void
    {
        $writer = new FilesystemWriter();
        $plan = $writer->plan([$this->dir . '/out/'], [$this->file('User.php', 'user')]);

        self::assertFalse($this->canLock(DirectoryLocks::path($this->dir . '/out')));

        $writer->apply($plan);

        self::assertTrue($this->canLock(DirectoryLocks::path($this->dir . '/out')));
    }

    public function testReleasesTheLockWithoutApplying(): void
    {
        $writer = new FilesystemWriter();
        $writer->plan([$this->dir . '/out'], [$this->file('User.php', 'user')]);

        $writer->release();

        self::assertTrue($this->canLock(DirectoryLocks::path($this->dir . '/out')));
    }

    public function testReleasesTheLockWhenTheWriterIsDropped(): void
    {
        $writer = new FilesystemWriter();
        $writer->plan([$this->dir . '/out'], []);
        unset($writer);

        self::assertTrue($this->canLock(DirectoryLocks::path($this->dir . '/out')));
    }

    public function testLetsTwoWritersOfOneProcessShareALock(): void
    {
        $first = new FilesystemWriter();
        $second = new FilesystemWriter();
        $first->plan([$this->dir . '/out'], []);

        // Would block forever if each writer took its own lock.
        $second->plan([$this->dir . '/out'], []);
        $first->release();

        self::assertFalse($this->canLock(DirectoryLocks::path($this->dir . '/out')));

        $second->release();

        self::assertTrue($this->canLock(DirectoryLocks::path($this->dir . '/out')));
    }

    public function testDeletesBeforeItWrites(): void
    {
        mkdir($this->dir . '/out');
        $path = $this->dir . '/out/User.php';
        file_put_contents($path, self::HEADER . 'old');

        // On a case-insensitive filesystem a class renamed from Foo to FOO plans exactly this for one file.
        (new FilesystemWriter())->apply(new WritePlan([FileChange::update($path, self::HEADER . 'new'), FileChange::delete($path)], [], []));

        self::assertSame(self::HEADER . 'new', file_get_contents($path));
    }

    public function testTreatsAManifestWithWindowsLineEndingsAsUnchanged(): void
    {
        $this->write([$this->file('User.php', 'user')]);
        $manifest = $this->dir . '/out/.dto-generator.manifest.json';
        file_put_contents($manifest, str_replace("\n", "\r\n", (string) file_get_contents($manifest)));

        self::assertFalse((new FilesystemWriter())->plan([$this->dir . '/out'], [$this->file('User.php', 'user')])->hasChanges());
    }

    public function testKnowsWhichManifestsAreNew(): void
    {
        $this->write([$this->file('User.php', 'user')]);

        $plan = (new FilesystemWriter())->plan([$this->dir . '/out', $this->dir . '/fresh'], [
            $this->file('User.php', 'changed'),
            new GeneratedFile($this->dir . '/fresh', 'Tag.php', self::HEADER . 'tag'),
        ]);

        self::assertFalse($plan->isNewManifest($this->dir . '/out/.dto-generator.manifest.json'));
        self::assertTrue($plan->isNewManifest($this->dir . '/fresh/.dto-generator.manifest.json'));
    }

    public function testGivesNewFilesTheUmaskPermissions(): void
    {
        $previous = umask(0002);

        try {
            $this->write([$this->file('User.php', 'user')]);
        } finally {
            umask($previous);
        }

        self::assertSame('0664', substr(sprintf('%o', fileperms($this->dir . '/out/User.php')), -4));
    }

    private function canLock(string $path): bool
    {
        $handle = fopen($path, 'c');
        self::assertIsResource($handle);
        $locked = flock($handle, LOCK_EX | LOCK_NB);
        fclose($handle);

        return $locked;
    }

    /**
     * @param list<GeneratedFile> $files
     */
    private function write(array $files): WritePlan
    {
        $writer = new FilesystemWriter();
        $plan = $writer->plan([$this->dir . '/out'], $files);
        $writer->apply($plan);

        return $plan;
    }

    private function file(string $relativePath, string $body): GeneratedFile
    {
        return new GeneratedFile($this->dir . '/out', $relativePath, self::HEADER . $body);
    }

    /**
     * @return list<array{string, string}>
     */
    private function summary(WritePlan $plan): array
    {
        return array_map(
            fn (FileChange $change): array => [$change->kind(), substr($change->path(), strlen($this->dir . '/out/'))],
            $plan->changes(),
        );
    }

    private static function remove(string $path): void
    {
        if (is_dir($path) && !is_link($path)) {
            chmod($path, 0755);
            foreach ((array) scandir($path) as $entry) {
                if ($entry !== '.' && $entry !== '..') {
                    self::remove($path . '/' . $entry);
                }
            }

            rmdir($path);
        } elseif (file_exists($path)) {
            unlink($path);
        }
    }
}
